### ISSUE TITLE
'dbtPowerUser.showCompiledSQL' not found

### ISSUE THREAD

**Issue by puruzio** [innoverio/vscode-dbt-power-user#100]
This extension used to work well, but a couple of months ago, it started giving me `command xxx not found` error whenever I try to use the extension from Ctrl+Shift+P menu.

I checked this following issue that mentions the same error message but it doesn't seem to apply to me as I'm not using devcontainer or anything like that.
https://github.com/innoverio/vscode-dbt-power-user/issues/78

I noticed the "Runtime Status" tab says "Not yet activated" when I open the extension detail in VS code.

Is there I can try to troubleshoot the issue? 

<Additional info>
DBT_PROFILES_DIR = r:\1.dbt

Dbt version 1.0.1
Plugin: -sqlserver 1.0.0

Manifest location
/dbt_projects/target/manifest.json

VS Code version 1.63.2

dbt Power User v0.5.9

**Comment by mdesmet** [comment]
the issue is that the extension can't be activated, could you check the console log through Help >> Toggle Developer tools and post the log. It might be that the extension can't read your dbt_project.yml file (invalid yaml).

**Comment by puruzio** [comment]
Absolutely nothing shows up in the developer console before and/or after the error message. Is there anything else I can try?

**Comment by puruzio** [comment]
Where does the extension look for the dbt_project.yml?

**Comment by mdesmet** [comment]
Everywhere in the opened folders within the vscode workspace.

**/dbt_project.yml
