### ISSUE TITLE
Stuck at `Detecting dbt`

### ISSUE THREAD

**Issue by danielzuluagas** [innoverio/vscode-dbt-power-user#101]
I try to open a project but the plug in is just stuck trying to find the project, I don't know what else do I need to configure.

**Comment by sandhein** [comment]
I am facing the same issue.
Did you find a solution to your problem?

When opening the debugger tools I see the following error message in VSCode:
![grafik](https://user-images.githubusercontent.com/26199754/152844374-efee1f19-f3e1-4e20-b6c2-8d5e77bc2754.png)

**Comment by sandhein** [comment]
Here is the output of `dbt --version`:
![grafik](https://user-images.githubusercontent.com/26199754/152934691-335e91cc-ebd4-41e0-90d3-b0d0719b1060.png)

The problem might be that pypi is not accessible from VS-Code. The computer I'm using is offline for security reasons. Is there a way to bypass this check or change the url which dbt uses to check for the latest version? We have a proxy repository which we use to install packages from pypi

**Comment by mdesmet** [comment]
ok, it's clear for me what to do, will push out a fix.

**Comment by danielzuluagas** [comment]
Here is my `dbt --version`

![image](https://user-images.githubusercontent.com/98325737/153074666-6787a8c8-aed7-4273-a87e-998fcf718a37.png)

**Comment by mdesmet** [comment]
fixed in 0.5.11. Let me know if it works for you!

**Comment by danielzuluagas** [comment]
This is what I'm getting now:

![image](https://user-images.githubusercontent.com/98325737/153075460-75a452d9-6888-453a-894e-04bb40900d72.png)

**Comment by mdesmet** [comment]
@danielzuluagas : i don't think you have the same issue. Did you check the console? See Help >> Toggle developer tools.

**Comment by danielzuluagas** [comment]
This is what I get in the Developer Tools

![image](https://user-images.githubusercontent.com/98325737/153076339-17ca4222-fe8b-4d12-b252-1e644db736d4.png)

**Comment by mdesmet** [comment]
The error is there: you need to select a python interpreter. All this is explained in the pinned issues.

**Comment by danielzuluagas** [comment]
I have the interpreter selected thought.

**Comment by mdesmet** [comment]
ic, otherwise dbt list would not return any values. So what exactly is your problem? Seems your environment is working, dbt list can only executes if it finds a dbt project.

**Comment by danielzuluagas** [comment]
I m anaged to fix the `dbt not installed` and now it can run `dbt list`:

![image](https://user-images.githubusercontent.com/98325737/153078493-338cdf34-3a2e-4b21-b457-30a6bc21b56f.png)

But for some reason it won't list my model in the dbt Power user tab:

![image](https://user-images.githubusercontent.com/98325737/153078546-43ea6257-8f18-40c8-b6e9-ddc7e846d58e.png)

**Comment by sandhein** [comment]
> fixed in 0.5.11. Let me know if it works for you!

Now it works like a charm :-).
Thank you for the prompt fix
