### ISSUE TITLE
Use zsh terminal env variables

### ISSUE THREAD

**Issue by jessedobbelaere** [innoverio/vscode-dbt-power-user#103]
When I hit the "compile" or "run" button on a dbt model, the terminal displays:

```
...
botocore.exceptions.NoCredentialsError: Unable to locate credentials
17:22:57  Encountered an error:
Runtime Error
  Runtime Error
    Unable to locate credentials
```

In https://github.com/innoverio/vscode-dbt-power-user/issues/84 I read that you can pass env variables via the settings, but it does not read env variables from the integrated terminal due to technical constraints.

In my workflow, we generate temporary AWS credentials by assuming a role ([AWS sts](https://docs.aws.amazon.com/STS/latest/APIReference/welcome.html)), and they only live as environment variables (not in `~/.aws/credentials`. The env vars are loaded as part of my `~/.zshrc` though. 

Is there any possibility to set these env variables on the vscode task? 
By allowing to specify to run the dbt task with `zsh`, like the integrated terminal does, so it executes the `.zshrc` on startup and sets the right environment variables?

**Comment by mdesmet** [comment]
I played a bit with it, and it seems to work like that on macos and the way you say could work. I can let the child process take over the env variables from the parent process. 

I will make a new release later, let me know if it works!

**Comment by jessedobbelaere** [comment]
Thanks @mdesmet ! The button in vscode starts a dbt compile tasks and runs without errors now!
