### ISSUE TITLE
"Upgrade button" fails

### ISSUE THREAD

**Issue by ljhopkins2** [innoverio/vscode-dbt-power-user#105]
As of v1.0.0, `pip install dbt` explicitly fails and `pip install dbt-<adapter>` [should be used instead](https://docs.getdbt.com/dbt-cli/install/pip).

Clicking the "Upgrade" button that dbt power user presents when it detects an out-of-date dbt version fails with the following error.

```
> Executing task:  pip install --upgrade dbt

Collecting dbt
  Downloading dbt-1.0.0.tar.gz (2.9 kB)
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'error'
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      
      As of v1.0.0, `pip install dbt` is no longer supported.
      Instead, please use one of the following.
      
      **To use dbt with your specific database, platform, or query engine:**
      
          pip install dbt-<adapter>
      
          See full list: https://docs.getdbt.com/docs/available-adapters
      
      **For developers of integrations with dbt Core:**
      
          pip install dbt-core
      
          Be advised, dbt Cores python API is not yet stable or documented
          (https://docs.getdbt.com/docs/running-a-dbt-project/dbt-api)
      
      **For the previous behavior of `pip install dbt`:**
      
          pip install dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.
```

**Comment by ljhopkins2** [comment]
I looked around to see if it was something I might submit a PR on, and the most straightforward solution appeared to be replacing `dbt` in the following two functions with `dbt-core dbt-postgres dbt-redshift dbt-snowflake dbt-bigquery`. Ideally, however, only the adapter(s) the user needs would be installed, and I wasn't confident in figuring that solution out.

https://github.com/innoverio/vscode-dbt-power-user/blob/3d8350571d1717f641d679f6909de520b32e9381/src/dbt_client/dbtCommandFactory.ts#L99-L117

**Comment by ljhopkins2** [comment]
The workaround here is to run `pip install --upgrade dbt-<adapter>` in a terminal in the VS Code environment and reload the VS Code window.

**Comment by mdesmet** [comment]
Hi @ljhopkins2 ,

Definitely open for PRs. Would be happy to get more people on board!

I think the right approach to this, would be to detect the installed adapters through dbt version and then try to update them using above code.

First step would be to detect the installed adapters here:

https://github.com/innoverio/vscode-dbt-power-user/blob/1a41a2ef5b0d1d6382cabb334542d66ab1504732/src/dbt_client/index.ts#L236-L256

Second step would be adapting above code to try to update each detected adapter.

**Comment by mdesmet** [comment]
The PR still has some TODO's, feel free to take over and complete the work.
