### ISSUE TITLE
Autocomplete does not work

### ISSUE THREAD

**Issue by jnoynaert** [innoverio/vscode-dbt-power-user#106]
Go to definition works, as well as code snippets (e.g. `ref` expanding to `{{ ref('model_name') }}`), but autocomplete for model names inside refs does not work.

version: 0.5.14
environment: dev container/remote
dbt: 1.0.0

**Comment by mdesmet** [comment]
Can you elaborate on this issue?

It will only work when you type "ref('", it actually triggers on the single or double quote.

<img width="528" alt="image" src="https://user-images.githubusercontent.com/9265503/158234377-6b584051-7ebd-4871-99ed-c4249c4c6cbc.png">

**Comment by jnoynaert** [comment]
That explains it--using the `ref` and `source` snippets from `vscode-dbt` already has the quotes in the generated text, so it never triggers.

I'll work around it with custom snippets with a higher priority. Thanks!

**Comment by mdesmet** [comment]
Can you make a PR with those snippets, if you get it working?

**Comment by jnoynaert** [comment]
After some quick testing, it was better to leave the default snippet. Then if you want autocompletion, `backspace` -> `ctrl` + `space` will get you the normal autocomplete experience for models/sources.

The alternative I tested was to change the snippet to exclude quotes and enable autocomplete within snippets--not sure if the extension can easily impact that user setting
