### ISSUE TITLE
Color missing on Tasks - dbt terminal

### ISSUE THREAD

**Issue by compilerqueen** [innoverio/vscode-dbt-power-user#107]
I'm looking for a way to ensure that the output of tasks kicked off by dbt power user (i.e. running an individual model, parent/child models) have the success/error colorization on the dbt output.

From reviewing the issues so far, I'm thinking this could either be an issue with the 'Tasks - dbt' terminal not colonizing as-expected, or more generally, with the dbt Power User tasks not correctly attaching to my existing open terminal.

I'm on Windows, VS Code is on the latest stable release, and dbt Power User is fully up-to-date. python and dbt are both installed in a virtual environment, which is selected as the environment for VS Code. `Tasks - dbt` terminal runs correctly in the venv. As far as I'm aware, I don't have any extensions trying to add/change colors on the terminal outputs (always happy to double-check anything specific). Default terminal is powershell. dbt version 0.21.0

If I manually run a model in the integrated terminal, I get colorization as expected: 
![image](https://user-images.githubusercontent.com/102758805/161131268-1ea08898-e6e0-47fb-8cf6-184c8a318a9f.png)

If I run via dbt power user, the `Tasks - dbt` terminal is created or used, and the output is missing color:
![image](https://user-images.githubusercontent.com/102758805/161130651-19b3ec60-07ea-4219-bcd8-6f1e835a6c29.png)

I tried removing all terminal windows and running, and the new `Tasks - dbt` terminal creates and runs the command. If I remove all terminal windows and create a focus a powershell terminal, the `Tasks - dbt` terminal is still created, runs, and is missing colors. Same with a command prompt type terminal. 

If the `Tasks - dbt` terminal already exists, then it will be reused by any new commands, as-expected.

Is this expected behavior with the colors missing from the `Tasks - dbt` terminal?
Any insights on how I can get color to appear on the `Tasks - dbt` terminal and/or route the commands to my already-open terminal window?

**Comment by mazum21** [comment]
I experience exactly the same issue.

**Comment by compilerqueen** [comment]
Interesting update--I provisioned a new dbt project in our environment recently, and for this one, the Tasks-dbt output *is* correctly colorized. So, same machine, same instance of the extension, different dbt project, different behavior. I'm going to dig around in project settings a bit more to see if I can find any differences. So far, the most salient difference is that one project has thousands of models and the other has about three, but I'd be surprised if that's the culprit.

**Comment by mdesmet** [comment]
Seems to consistently work in my projects.

<img width="886" alt="image" src="https://user-images.githubusercontent.com/9265503/173446950-c3ddbea9-29d0-46a8-b0e0-67c2c34a6015.png">

The code handling the terminal output is here if that helps:

https://github.com/innoverio/vscode-dbt-power-user/blob/7495fee435f9271924d0be874a66b530ac4b6a73/src/commandProcessExecution.ts#L74-L93

**Comment by compilerqueen** [comment]
It's now working consistently for me after upgrading to dbt 1.1.0. I suspect that the different behavior I was noticing in the alternate project earlier was due to having a different version of dbt running in that project (I use different venvs for each repo).

If it wasn't a specific version bug on the coloration, then it may have been a bug in the interaction between that version and colorization settings.

@mazum21 you might try updating dbt and see if the colors work again!

Since as far as I can tell this issue isn't directly related to dbt power user and I can't currently reproduce it, I'm closing this issue.
