### ISSUE TITLE
Add plugin option "use project dir for profiles"

### ISSUE THREAD

**Issue by xemuliam** [innoverio/vscode-dbt-power-user#108]
If you work with many DBT projects on different envs/machines it is much more convenient to keep `profiles.yml` file in each project folder. However the extension doesn't support this kind of configuration (or I can't find that option at least).
Is there any chance to add plugin settings like "use project dir for profiles" and if this option has been chosen then plugin will be adding smth. like `--profiles-dir $PWD` to any DBT command from its scope to show models, dependencies, to run models etc.?

**Comment by mdesmet** [comment]
You can use environment variables as mentioned in #84

**Comment by xemuliam** [comment]
@mdesmet, Thanks for suggestion. However it doesn't help to work with individual, project-based profiles stored in project folders w/o continuous changing env variables.. If you use single common storage for all profiles then it will be completely different approach and you can use it easily. My question was related to totally different approach which is not supported by plugin at the moment at all.

**Comment by mdesmet** [comment]
Have you tried setting it to `DBT_PROFILES_DIR=./<profilesdir>`I think that could work, as dbt starts in the working dir and will lookup that path in your project.

**Comment by xemuliam** [comment]
Imagine: I work with one project for some time then switch to another one then to third one then back to first one.
The only way to do that at the moment is to use single common `profiles.yml` for all projects.
What if I want to use individual `profile.yml` files which will be inside project folders? The only way at the moment is to switch env variables ech time when I switch the project. Convenient? Nope!
This is why I've asked to add one setting to plugin just to ensure it will be automatically use current project dir to use `profiles.yml` inside dir.

**Comment by mdesmet** [comment]
I fully understand what you are saying. I tried out what I told you in the earlier comment and it just works.

```
❯ cd ~/IdeaProjects/ov-zone-loopbanen
❯ mkdir profiles
❯ cp ~/.dbt/profiles.yml ./profiles/
❯ export DBT_PROFILES_DIR=./profiles
❯ code .
```

It will enable you to put your specific profile in your project folder and just take that. As long as you have a stable path from your dbt project directory, there is no need to change environment variables for every project.

**Comment by xemuliam** [comment]
Looks like there is no way to add such setting into plugin. At least it looks like that. It's a pity :(

**Comment by mdesmet** [comment]
I think you just need to `export DBT_PROFILES_DIR=.`, by using `$PWD` your are actually setting an absolute path, while you want a relative path.

**Comment by mdesmet** [comment]
You can now set your profiles dir in the config in `dbt.profilesDirOverride`. Let me know if that works for you.

**Comment by brandon-segal** [comment]
I have a similar issue where dbt.profilesDirOverride does not seem to resolve relative paths. It is able to resolve absolute paths but this can be an issue when you plan on sharing the workspace settings with a team

**Comment by cecabrera** [comment]
I am having that same issue. The configuration I have in the `settings.json` is the following:

```
"terminal.integrated.env.osx": {
    "DBT_PROFILES_DIR": "${workspaceFolder}/transform/"
    , "DBT_ENV_HOST": ""
    , "DBT_ENV_PORT": ""
    , "DBT_ENV_USERNAME": ""
    , "DBT_ENV_SECRET_PASSWORD": ""
    , "DBT_ENV_DBNAME": ""
    , "DBT_ENV_SCHEMA": ""
    }
```

The dbt executor is located at the `transform` folder and the profile name is `bi`. I can run it using terminal by placing it at the `trasnform` level. When trying to use DBT Power User I the error:
```
dbt configuration is invalid : Runtime Error
  Could not find profile named 'bi'
```

Appreciate any help or support! Thank you :)

**Comment by congnc-anz** [comment]
I did 
```
export DBT_PROFILES_DIR=$PWD/dbt/profiles
export DBT_PROJECT_DIR=$PWD/dbt
```

And `dbt debug` command works well  but I got error message on problem tab as below, no lineage can be generated
```
dbt configuration is invalid : Runtime Error
 Could not find profile named 'default'
```
