### ISSUE TITLE
Very high "Electron" CPU usage with dbt power user enabled

### ISSUE THREAD

**Issue by joshfluitsma** [innoverio/vscode-dbt-power-user#109]
Whenever I install and enable dbt Power User, the process called "Electron" (which is always active while VSC is open) starts using 100% of CPU. When quitting VSC, the process stays and stays at 100%. After relaunching VSC a second Electron process opens and also goes up to 100% CPU, and this every-time I reopen VSC. I have to manually force quit the processes.
My CPU temps go up to 80-90 while idling when I do this.

I have since uninstalled et re-installed dbt power user many times and whenever it's uninstalled I have no issue whatsoever.
Of course this makes the extension unusable for me as VSC is always open and I don't want to have high CPU usage all the time.

Any idea where this might come from?

**Comment by mdesmet** [comment]
how many models are in your project?

**Comment by mdesmet** [comment]
Now every project uses a single Python process. Therefore I would expect this issue to be resolved. If not please reopen.
