### ISSUE TITLE
Add option to run the model in the current terminal

### ISSUE THREAD

**Issue by camfrout** [innoverio/vscode-dbt-power-user#11]
I have installed dbt in a virtual environment (due to different projects I work on requiring different dbt versions), and when I click on the run button, because a new terminal is created, the virtual environment is not activated and the `dbt run` command fails.

Even if I set my interpereter in  VSCode`Python: Select Interpreter` in my workspace to the correct one, clicking on the run button tries to execute `dbt run` before the venv is activated.

**Comment by mdesmet** [comment]
Hi @camfrout ,

Thanks for raising the issue. I was able to reproduce the issue and made the following change: it will now reuse the existing terminal or create a new one if none is present (that case will still fail for now). I would have preferred to run the command after the VENV activation, and looked a bit in the vscode python plugin, but it will require more deep investigation. At least you should be able to use the feature now.

Can you let us know if it is working?

**Comment by camfrout** [comment]
Hi. Thanks for the quick reply.

I installed the new version of the extension but now clicking on the play button doesn't do anything when I already have a terminal open. If no terminal is open, it creates a new DBT one (as before) and as expected still fails because of the virtual environment.

**Comment by mdesmet** [comment]
That's interesting. It's working on my computer... Where did i hear that before. i've tested on Windows + WSL2 (without venv) and Windows (with venv).

![graph](https://user-images.githubusercontent.com/9265503/91694666-3f0cfd80-eb6d-11ea-82d1-d46e158fdcb9.gif)

You could check if you see any errors in the console (Help -> Toggle developer tools)
What OS are you using?

**Comment by camfrout** [comment]
Hi! Thanks for replying.

OK, so if I try to click on the run buttons in Parent Models and Children Models, it works! But if I try to click on the run button at the top of the model I am editing, it is following the behaviour I described before.

I am using VS Code Insider running on Mac OS
And there is no error showing up in the console unfortunately.

**Comment by ShaoYuan-Weng** [comment]
Hi @camfrout,

We just released a new version that fixed this issue. I tested on my Mac and it worked. Sorry that we didn't notice this bug earlier. 

Could you please test the new version and if it works, could you close the issue ? And also if you have other ideas or find other bugs, just drop us a line whenever you want :) Thank you again for your time and feedback !

**Comment by camfrout** [comment]
Thanks! It's working fine now.
