### ISSUE TITLE
Add "go to definition" functionality for doc() references

### ISSUE THREAD

**Issue by rumbin** [innoverio/vscode-dbt-power-user#110]
While the "go to definition" functionality (F12) works nicely for `ref()` and `source()` functions, it does not seem to be implemented for `doc()` yet.

Navigating in a markdown wile which has many docs blocks included can be a tedious task. Therefore it would be beautiful if we could have the "go to definition" functionality implemented here.

**Comment by mdesmet** [comment]
Fixed in 0.10.0
