### ISSUE TITLE
dbt shows connected but extension has zero functionality

### ISSUE THREAD

**Issue by elctrc-rhino** [innoverio/vscode-dbt-power-user#111]
After installing dbt-power-user and confirming dbt is connected, none of the functionality of the extension is working. Nothing populates in the parent/child models area and none of my models link out to definitions, nor does autocomplete work. 

I believe this is most closely related to the following issues: [Editor functionality not working](https://github.com/innoverio/vscode-dbt-power-user/issues/57) and [Cannot read manifest](https://github.com/innoverio/vscode-dbt-power-user/issues/81). I have updated to the latest version of both VS Code and dbt-power-user. I have tried removing other plugins. I have tried opening the base dbt jaffleshop code but have the same issue. The console seems to be showing errors in the dbt code but I don't know that it's related (based on the other tickets). An example of one of the console errors:

```File not found at '/dbt/macros/generate_schema_name.sql', probably compiled is outdated! Error: ENOENT: no such file or directory, open '/dbt/macros/generate_schema_name.sql'```

In the above case, the file is definitely there, and works as expected and does not give any errors in dbt. But that is just one of what look like dozens of similar errors. It seems like possibly a red herring. When I just open the base jaffleshop code, for example, it just gives different errors, like missing the "manifest.json" file - again, perhaps just a red herring.

```
System info:
Mac OS Monterey 12.3.1
VS Code 1.66.2
dbt Power User v0.5.16
```

**Comment by mdesmet** [comment]
Are you using a docker container setup where the path in your container doesn't match with the filesystem's path? 

In that case you should setup your vscode to [open the workspace in the container](https://code.visualstudio.com/docs/remote/containers#_open-an-existing-workspace-in-a-container).

**Comment by krvrd** [comment]
I don't use Docker container for a project but am stuck with the same issue. I can't surf through models ref and I don't see any information in a dbt-power-user tab. 

MacOS 12
dbt v.1.1.1 installed by homebrew
vscod shows that dbt connected

**Comment by korompaiistvan** [comment]
did y'all associate sql files with jinja-sql? I had this issue when I forgot that step

**Comment by elctrc-rhino** [comment]
Yup. Not using a Docker container and I have associated the files with jinja-sql.

**Comment by mdesmet** [comment]
Do you still have the same issue with latest version? If so please reopen the issue.
