### ISSUE TITLE
Detecting dbt not working due to Regex IS_LATEST_VERSION

### ISSUE THREAD

**Issue by sandhein** [innoverio/vscode-dbt-power-user#119]
The extension is not working for me, as it is stuck during detection of dbt version, due the following error:
![grafik](https://user-images.githubusercontent.com/26199754/177554967-c3b36e51-d82a-40c7-9a49-6dfa9ebdf9a0.png)

The issue has already been fixed in 0.5.11, but is now occurring again with 0.6.2:
[https://github.com/innoverio/vscode-dbt-power-user/issues/101](url)

Could you please integrate the fix in the latest version?

Thanks

**Comment by justmytwospence** [comment]
What version of DBT are you on?

**Comment by sandhein** [comment]
I'm on version 1.1.0

**Comment by sgoley** [comment]
Also having this issue on dbt version 1.2.1

**Comment by mdesmet** [comment]
The extension now just logs a warning in case of a failing version check.

**Comment by sandhein** [comment]
Thanks @mdesmet for fixing this. Is the fix already integrated in the latest version?

**Comment by mdesmet** [comment]
Yes
