### ISSUE TITLE
Support monorepo projects (multiple dbt projects within the same folder)

### ISSUE THREAD

**Issue by mdesmet** [innoverio/vscode-dbt-power-user#12]

**Comment by Limess** [comment]
I presume this would also mean support for single projects in nested directories? I installed this extension but nothing happened, I assume because we nest our DBT project in a `dbt` directory?

**Comment by mdesmet** [comment]
Currently the workaround is indeed to set the directory to an individual dbt project. The extension will only be activated if it finds the dbt_project.yml file in the root folder. 

We could setup this monorepo support but it will require some refactoring in how the manifest work. Currently it's a singleton, while in the case of a monorepo it should be create a manifest per found project. It's definitely possible to support this.

**Comment by bodschut** [comment]
Could you already allow the configuration of the project directory? In our case, the dbt project is in a subdirectory of the repository (but it's only a single dbt project), so just setting the correct folder could already fix this.

**Comment by mdesmet** [comment]
We will first fix the issue with multiple workspace folders opened at once (we will need to create a manifest for each folder). 

Then we will look into adding this configuration or support discovery of dbt projects within a repo.

**Comment by mdesmet** [comment]
We just released the support for multiple workspace folders and will look into supporting monorepo's in next iteration.

**Comment by mdesmet** [comment]
Hey folks, 

In version 0.3.2 monorepo's are supported. The extension will automatically discover any dbt projects ignoring the dbt packages within dbt projects and create the associated manifest.

Let us know of any issues you encounter!

**Comment by Limess** [comment]
Monorepo support doesn't seem to be working for me, does anything need to be configured?

For reference we have our dbt project in a `dbt` folder in our repo

**Comment by mdesmet** [comment]
Sorry my mistake, I had tested by putting another project inside an existing dbt project and overlooked the extension activation part. So the code was working just in the case of no dbt_project.yml in the root folder, the extension was not getting activated.

Now it will activate if there is any dbt_project.yml wherever in the workspace. Fixed in 0.3.5!

Let me know if it works!

**Comment by Limess** [comment]
That works great, this is amazing! Thanks so much
