### ISSUE TITLE
Possible to override executable?

### ISSUE THREAD

**Issue by aaronsteers** [innoverio/vscode-dbt-power-user#120]
I'd like to provide a wrapper around dbt and to use that as a drop-in replacement for dbt. Is that possible in this implementation?

I see noted here...

- https://github.com/innoverio/vscode-dbt-power-user/issues/87

that the recommended way to use an alternative dbt executable is to change the Python interpreter. Is this strictly required due to python-level dependencies and/or python imports? Or would it be feasible to create a PR that provides a direct path to a custom dbt executable and/or a CLI-based dbt wrapper?

In our use case the wrapper ([Meltano](meltano.com)) also handles environment variable injection and secrets management - so I don't know if overriding the Python interpreter and venv alone would be sufficient.

**Comment by mdesmet** [comment]
I'm happy to work with you guys to make this work. At the moment we execute the commands through Python and obviously it's important to execute within the correct Python environment (as dbt supports multiple adapters and projects might use different dbt versions), this way we can provide the same experience as using the terminal.

You may contact me on the dbt slack and we can setup a call if that would be of any interest.

**Comment by pezon** [comment]
Hi guys, any update on this issue? I am evaluating using DBT Power User and Meltano for my team. I would like to use Meltano to create and manage pipeline projects. Because Meltano is setting the environment, I'd like DBT Power User to use execute `meltano invoke dbt-x` instead of `dbt`.

**Comment by tayloramurphy** [comment]
@aaronsteers are you working on this? I don't know if we're ready to commit to it as an org, but as a personal effort right now I think it makes sense.

**Comment by aaronsteers** [comment]
@tayloramurphy and @pezon - I'm not personally working on this and Meltano isn't actively prioritizing as of now. However, I know @z3z1ma's fork does have the needed change. That fork has tons of other things as well though like the dbt-osmosis features, which is a lot more extra scope than would be warranted for just the executable override.

**Comment by mdesmet** [comment]
In 0.8.0 there is a new setting `dbt.dbtPythonPathOverride` to override the python executable, however I personally don't test with Meltano so I'm not sure if it is working or not.

**Comment by z3z1ma** [comment]
@mdesmet
I can vouch it does work, I added it and use it for that reason specifically. The only caveat on the Meltano side is you need to expose the python executable in the plugins venv. Which I do through `commands` and its `executable` config option. We should plant it somewhere as documentation. 
`dbt.dbtPythonPathOverride` can be added to `settings.json` and committed so all users of the repo have a consistent experience since meltano projects are the same structure across all installations.

**Comment by z3z1ma** [comment]
Not sure if the documentation would be better here or on Meltano's side though.

**Comment by mdesmet** [comment]
I'm assuming the override works as expected. Please reopen if not.

**Comment by aaronsteers** [comment]
Thanks very much @mdesmet. We've not been able to regroup for retest, but I take from @z3z1ma that we're in a good place as soon as we come back to revisit.

cc @pnadolny13 in case you have time to test out in our `squared` project.
