### ISSUE TITLE
Jump to reference not working, parent/child models in view not showing

### ISSUE THREAD

**Issue by eriwang** [innoverio/vscode-dbt-power-user#121]
Hello! First time making a GH Issue here, let me know if I'm missing some information in the issue request.

# Version Information

OS: macOS 12.5
DBT Version: 1.2.0 (via VS Code pip virtualenv, and also via homebrew)
DBT Power User Version: 0.6.2 (see "Attempts to Resolve" - 0.5.12 works for me, 0.5.13 doesn't)
VS Code Version: 1.7.0

# Issue

After I wait for the `dbt list` in the "Tasks - dbt" terminal to complete, I try doing "Go to Reference" on a ref, and nothing happens beyond an error message:

![image](https://user-images.githubusercontent.com/12244495/183702103-8fc8aea3-e180-407d-b8c5-6477d6b46e44.png)

The DBT Power User side pane that shows Parent and Child models is also blank:

![image](https://user-images.githubusercontent.com/12244495/183702014-e4a1fe7a-e4b7-41dc-b48f-418ddabb4c09.png)

It's worth calling out that in the `exthost.log` file, I get a bunch of these messages, specifically they seem to pop up whenever I try doing "Go to Reference":

```
[2022-08-09 11:03:44.046] [exthost] [error] [innoverio.vscode-dbt-power-user] provider FAILED
[2022-08-09 11:03:44.046] [exthost] [error] undefined
[2022-08-09 11:03:44.046] [exthost] [error] [innoverio.vscode-dbt-power-user] provider FAILED
[2022-08-09 11:03:44.046] [exthost] [error] undefined
[2022-08-09 11:05:15.972] [exthost] [error] [innoverio.vscode-dbt-power-user] provider FAILED
[2022-08-09 11:05:15.972] [exthost] [error] undefined
```

# Attempts to Resolve

I reinstalling the extension, reopening VS Code, doing a sanity `dbt clean` just in case something weird happened there, and none of those worked. However, I was able to get the functionality (both the side pane model preview and the "Go to Reference") to work again by downgrading, the most recent version I was able to get it to work is 0.5.12 - upgrading to 0.5.13 gives me issues.

Please let me know if I can provide any other information that helps debug the issue! Thanks!

**Comment by mdesmet** [comment]
Most likely it is related to changing the yaml library. See https://github.com/innoverio/vscode-dbt-power-user/commit/1a41a2ef5b0d1d6382cabb334542d66ab1504732

Could you try finding what section of your yaml is causing issues and posting it here?
