### ISSUE TITLE
Run current model command broken; "Command dbtPowerUser.runCurrentModel not found"

### ISSUE THREAD

**Issue by Luttik** [innoverio/vscode-dbt-power-user#123]
Hi,

I am getting the following error both when using the run button as well as when I use the run command from the vscode command pallette:
![image](https://user-images.githubusercontent.com/6634187/189296735-51a07a6f-75ef-4902-8112-caed6a636016.png)

This seems like a straight up bug...

I am getting a similar message for:
- show compiled sql
- show run sql

**Comment by mdesmet** [comment]
This looks like the extension did not activate. Is this happening on every project? You have contributed to this repo already so i assume you know how to debug the extension?

**Comment by Luttik** [comment]
Hé Mdesmet. I only changed configuration in the package.json, so I have no clue. But I assume it might have something to do with me having run custom-builds before... Therefore, I'll close the issue since this might not be reproducable.
