### ISSUE TITLE
Could not find profile <project_name>

### ISSUE THREAD

**Issue by OHDMax** [innoverio/vscode-dbt-power-user#126]
Hello,

first things first, thank you for maintaining this extremly helpful extension!

However with the newest update the extension broke for me and so far profiles seem to be the culprit. It seemst that the extension assumes that the dbt-profile to use is named the same as the dbt-project's name. However with my dbt project that's not the case. It uses a profile called "default". dbt knows about this because you can set the profile with the `profile` property inside of the dbt_project.yml.

Would it be possible to use the value of the profiles property as profile name instead of the project name? This would prevent surprises like this.

**Comment by mdesmet** [comment]
Fixed in 0.7.1

**Comment by OHDMax** [comment]
That was fast, thank you!

**Comment by mdesmet** [comment]
Please let us know if you encounter any other issues.
