### ISSUE TITLE
Compatibility with limit for SQL Server

### ISSUE THREAD

**Issue by matsonj** [innoverio/vscode-dbt-power-user#128]
When query is passed to SQL Server for execution, it includes "limit 200" on the query. However, SQL Server does not like this syntax since T-SQL is not postgres compatible. 

It looks like limit is attached here: [dbtCommandFactory.ts](https://github.com/innoverio/vscode-dbt-power-user/blob/master/src/dbt_client/dbtCommandFactory.ts)

```
try:
    import decimal
    import json
    import re
    import sys
    import traceback
    import orjson
    from dbt_osmosis.core.osmosis import DbtOsmosis
    runner = DbtOsmosis(
        project_dir=r"${projectRoot.fsPath.replace(/"/g, '\\"')}",
        target=r"${target.replace(/"/g, '\\"')}",
    )
    query = """${sql.replace(/"/g, '\\"')}"""
    query_with_limit = f"select * from ({query}) as osmosis_query **limit ${limit}**"
    result = runner.execute_sql(query_with_limit)
except Exception as exc:
    eprint(json_dumps({"message": str(exc), "data": traceback.format_exc()}))
    sys.exit(-1)
```

The fix for SQL Server is detecting when the adapter type is SQL Server and passing the following syntax:

```
query_with_limit =  f"select top ${limit} * from ({query}) as osmosis_query "
```

**Comment by matsonj** [comment]
FYI with following config
```
"dbt.queryTemplate": "select top {limit} * from ({query})"
```

I get error: ('42000', "[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'from'. (156) (SQLExecDirectW)") 

This is because sql server requires all subqueries to be aliased.

Valid Syntax: 
 ```SELECT TOP 200 * FROM (SELECT 1 as test) AS a"```

Invalid Syntax:
 ```SELECT TOP 200 * FROM (SELECT 1 as test)```

It looks like 'queryRegex' is causing Invalid syntax to be generated even with the template
```"dbt.queryTemplate": "select {limit} * from ({query}) as A"```

**Comment by mdesmet** [comment]
I can't immediately simulate your issue as I don't have sql server but the regex seems to work fine.

with queryTemplate configured as `select top {limit} * from ({query}) as osmosis_query`

```
import re


query = """\
select top 500 * from (select
    id as order_id,
    user_id as customer_id,
    order_date,
    status

from ordersdb.public.orders ) as osmosis_query
"""
print(re.search(r"select top 500 \* from \(([\w\W]+)\) as osmosis_query", query).groups()[0])
```

**Comment by matsonj** [comment]
using the following queryTemplate: ```"dbt.queryTemplate": "select {limit} * from ({query}) as osmosis_query"```

I get the following error when executing the model ```select 1 as test```

>[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'from'. (156) (SQLExecDirectW); [42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'as'. (156)\")\n"

Is there a way to see the SQL generated?

**Comment by mdesmet** [comment]
You should use 
```
"dbt.queryTemplate": "select top {limit} * from ({query}) as osmosis_query"
```

**Comment by matsonj** [comment]
its the little things...

<img width="433" alt="image" src="https://user-images.githubusercontent.com/16811433/192585553-560655c0-3628-4574-a5a9-f86d759e59cb.png">

**Comment by Trymzet** [comment]
This doesn't work for CTEs, breaks with:
```python
[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Incorrect syntax near the keyword 'with'. (156) (SQLExecDirectW)
```

**Comment by thebroberts** [comment]
I'm using Synapse dedicated so the OFFSET.. LIMIT method doesn't help. As a workaround to the workaround, I am using:

`set rowcount {limit}; {query}`

This isn't ideal from a query optimizer standpoint, but it's working nicely even for models with CTEs.

**Comment by mdesmet** [comment]
Thanks @thebroberts for helping out, this is highly appreciated! Can you please make a PR and add this to the documentation?
