### ISSUE TITLE
Allow customisation of run model

### ISSUE THREAD

**Issue by calvingiles** [innoverio/vscode-dbt-power-user#13]
Currently running a model from the file uses a [hard-coded run command](https://github.com/innoverio/vscode-dbt-power-user/blob/master/src/commands/runModel.ts#L39):
```
terminal.sendText(`dbt run --model ${plusOperatorLeft}${modelName}${plusOperatorRight}`);
```
which works great, except it assumes the default dbt setup is best. I have found it preferable to use `--partial-parse` and `--warn-error` global args, and `--threads=20` run args, and I am sure others have found args that work best to their liking.

It would be great if the vscode-dbt-power-user plugin could take global args and run args in it's setup somewhere to support these.

I am happy to try to contribute but haven't written any JS before and only started using VSCode this afternoon so will need some pointers.

**Comment by mdesmet** [comment]
Hi @calvingiles, we usually configure these in profiles.yml themselves. But shouldn't be too hard to implement this!

Basically what you need to is:

- Configure a setting with the additional params in settings.json (see the README) for example (probably best prefixed with the full name of the extension (innoverio.vscode-dbt-power-user)
- Use vscode.workspace.getConfiguration(section?: string | undefined, scope?: ConfigurationScope | null): WorkspaceConfiguration
 (See https://code.visualstudio.com/api/references/vscode-api#workspace) and add it to the run model string

If you need help, just ping us. We definitely welcome your PR!

**Comment by Limess** [comment]
We also use a custom DBT run command as we have DBT in a separate python VENV in a monorepo folder (`dbt/.venv`) (we do `poetry run dbt` using https://python-poetry.org/)
