### ISSUE TITLE
Cannot run on windows using dbt on windows  Get error SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

### ISSUE THREAD

**Issue by needbrew** [innoverio/vscode-dbt-power-user#131]
Models show up in the extension but when trying to execute anything I get the error
SyntaxError: (unicode error) 'unicodeescape' codec can't decode bytes in position 2-3: truncated \UXXXXXXXX escape

Windows 10, DBT 1.2, python 3.9 all on windows

**Comment by mdesmet** [comment]
Resolved in 0.7.9
