### ISSUE TITLE
Hover to show definition preview not working...

### ISSUE THREAD

**Issue by GJmelody** [innoverio/vscode-dbt-power-user#133]
When I click the model names it goes to the definition file but preview seems not working. See screenshot below (the little grey box is empty):

<img width="567" alt="image" src="https://user-images.githubusercontent.com/31524706/192912054-23d93774-ad4f-45f3-a214-2eab8c2e5eff.png">

**Comment by mdesmet** [comment]
Could you provide more details. For example which OS you are using?

**Comment by MaxCSHan** [comment]
Hi @mdesmet, 
I am having same issue here. 
The intellisense shows nothing but I can still go to the definition file. 
<img width="456" alt="Screen Shot 2022-10-26 at 10 59 28 AM" src="https://user-images.githubusercontent.com/64484802/197924292-4d3a7e5b-7f8b-434f-8164-13f124c73e83.png">
With environment:
`02:31:33  Running with dbt=1.3.0
dbt version: 1.3.0
python version: 3.9.15
python path: /opt/homebrew/Cellar/dbt-bigquery/1.3.0/libexec/bin/python
os info: macOS-12.5-arm64-arm-64bit`

**Comment by mdesmet** [comment]
I found the issue. Will be released shortly.
