### ISSUE TITLE
dbt packages uses version information in project detection

### ISSUE THREAD

**Issue by mdesmet** [innoverio/vscode-dbt-power-user#158]
Hi All,

I use VSCode.

- dbt version: 1.0.8
- python version: 3.9.12
- os info: macOS-11.6.2-x86_64-i386-64bit
- pipenv to create virtualenv's
- zsh as my terminal
- snowflake

I have dbt Power User installed but quite a few the features don't work.
I can't get it to do any of the following:

- Run current model
- terminal runs dbt list.
- parent / child model navigation
- no compiled SQL launch
- no hyperlink go to definition
- autocompletion

At startup, the terminal displays the following (truncating path to the project directory):
```sh
An error occurred while trying to refresh the project configuration: Error: ENOENT: no such file or directory, open '../zion-data-modeling/dbt_packages/dbt-expectations-0.5.5/dbt_project.yml'
An error occurred while trying to refresh the project configuration: Error: ENOENT: no such file or directory, open '../zion-data-modeling/dbt_packages/dbt-expectations-0.5.5/integration_tests/dbt_project.yml'
An error occurred while trying to refresh the project configuration: Error: ENOENT: no such file or directory, open '../zion-data-modeling/dbt_packages/dbt-date-0.5.7/dbt_project.yml'
An error occurred while trying to refresh the project configuration: Error: ENOENT: no such file or directory, open '../zion-data-modeling/dbt_packages/dbt-date-0.5.7/integration_tests/dbt_project.yml'
An error occurred while trying to refresh the project configuration: Error: ENOENT: no such file or directory, open '../zion-data-modeling/dbt_packages/dbt-utils-0.8.6/dbt_project.yml'
An error occurred while trying to refresh the project configuration: Error: ENOENT: no such file or directory, open '../zion-data-modeling/dbt_packages/dbt-utils-0.8.6/integration_tests/dbt_project.yml'
```

The `dbt_expectations` package is in the root of the project, but not with the names inclusive of version as alluded to with the ENOENT error:
<img width="199" alt="image" src="https://user-images.githubusercontent.com/94391358/186527119-8d6773f8-fe90-46c7-bfa2-51ae4a037949.png">
But, these get installed via the `dbt_expectations` package in my `packages.yml` in the root of the project:
<img width="286" alt="image" src="https://user-images.githubusercontent.com/94391358/186527508-e93fedb0-da8f-4cb8-a635-daaa1c0557b9.png">

Any thoughts on what is going on here and how I might get around this issue?
Appreciate any help with this in advance!

_Originally posted by @datanerd09 in https://github.com/innoverio/vscode-dbt-power-user/discussions/44#discussioncomment-3469435_

**Comment by mdesmet** [comment]
@datanerd09 : can you retest this with latest version?

**Comment by datanerd09** [comment]
So running the latest version of this plugin (v0.8.1), I don't get objects to show up in the GUI (regardless if I have a model file open or not). Other parts seem to work (like actually running the models, tests, etc.), though this seems to be done with a different interpreter than I expected.

The requirements.txt stands up a virtual environment using this path: `zion-data-modeling/venv/bin/python3`.
The `Tasks - dbt` window appears to be running python from here though: `/usr/local/bin/python3`

<img width="1411" alt="image" src="https://user-images.githubusercontent.com/94391358/198302160-9b77a62a-6b46-4a69-830d-9b9cc607afb9.png">

Not sure if this has anything to do with the experience captured here though.

**Comment by datanerd09** [comment]
So it still runs models, tests, etc. picking the interpreter associated with my venv, but there's still nothing shows in the GUI.

**Comment by mdesmet** [comment]
If the python bridge can't be started you should at least see one error.

**Comment by mdesmet** [comment]
I don't have enough information to reproduce your issue. Also the parent, child and tests are only displayed when you have a dbt model selected.

In any case you should see an error if for some reason the Python integration can't be started. Could you make a video of the startup process and what you exactly try?

**Comment by datanerd09** [comment]
The above is with a model selected. Sure, I'll see if put something a little more detailed together.

**Comment by datanerd09** [comment]
https://user-images.githubusercontent.com/94391358/199033854-35da15fd-9a67-4eda-a954-0cc8b9d7182c.mov


https://user-images.githubusercontent.com/94391358/199033878-5845c736-aaa7-40a2-96c1-4b6d6144b598.mov

**Comment by mdesmet** [comment]
I don't understand what you are trying to say in the last section, but obviously it's not normal to find `dbt_project.yml` files in the compiled folder of a project. Also according to the error message your folder is called dbt_project.yml.

The extension just looks for any `dbt_project.yml` files and tries to register the containing folder as a project.

**Comment by datanerd09** [comment]
So basically, find a way around this reference in the directory or expect complications with the plugin. 
The looking for _any_ `dbt_project.yml` is what I needed here. Thank you.
