### ISSUE TITLE
Add lineage graph

### ISSUE THREAD

**Issue by mdesmet** [innoverio/vscode-dbt-power-user#16]

**Comment by jlpjavi** [comment]
I would be interested in helping develop this feature if you can guide me a little bit!

**Comment by mdesmet** [comment]
Contact me on dbt slack. I'll be happy to help you!

**Comment by orellabac** [comment]
Yes I will love to help. Initially I was just thinking on generating the lineage and add a webview to present it. But I 'll love to have a nicer view like the one in the web ide of dbt.

Let me know if you already have some thoughts how to implemented this and I can give you a hand.

**Comment by GiorgiModebadzeW** [comment]
@mdesmet is marmaid.js something you might consider to address this or is it too basic for this purpose?

**Comment by mdesmet** [comment]
Please have a look at #309 and help @jlpjavi .

I don't really have any preference regarding diagram library but prefer one that is easy to use, high performance and is extensible.
