### ISSUE TITLE
'charmap' codec can't encode characters in position x-y: character maps to <undefined>

### ISSUE THREAD

**Issue by thomasgjerdekog** [innoverio/vscode-dbt-power-user#177]
### Expected behavior

When running the sql of a model using the "Execute dbt SQL" button, it should display the data in the results window.

### Actual behavior

When the returned data contains special characters from other locales (i.e.: Chinese characters), the result window fails with the error message: `'charmap' codec can't encode characters in position x-y: character maps to <undefined>` (x and y varies between different queries)

### Steps To Reproduce

Create a table in Snowflake and fill at least one column in one row with Chinese characters (i.e.: 生产). Define the table as a source and reference it from a base model. Run the code in the base model using the "Execute dbt SQL" button in dbt power user.

### Log output/Screenshots

```
{
    "message": "'charmap' codec can't encode characters in position 374178-374180: character maps to <undefined>",
    "data": "Traceback (most recent call last):\n  File \"<string>\", line 268, in <module>\n  File \"c:\\<removed_directory_path_from_output>.dbtenv\\lib\\site-packages\\colorama\\ansitowin32.py\", line 47, in write\n    self.__convertor.write(text)\n  File \"c:\\<removed_directory_path_from_output>.dbtenv\\lib\\site-packages\\colorama\\ansitowin32.py\", line 170, in write\n    self.write_and_convert(text)\n  File \"c:\\<removed_directory_path_from_output>.dbtenv\\lib\\site-packages\\colorama\\ansitowin32.py\", line 198, in write_and_convert\n    self.write_plain_text(text, cursor, len(text))\n  File \"c:\\<removed_directory_path_from_output>.dbtenv\\lib\\site-packages\\colorama\\ansitowin32.py\", line 203, in write_plain_text\n    self.wrapped.write(text[start:end])\n  File \"C:\\Program Files\\Python310\\Lib\\encodings\\cp1252.py\", line 19, in encode\n    return codecs.charmap_encode(input,self.errors,encoding_table)[0]\nUnicodeEncodeError: 'charmap' codec can't encode characters in position 374178-374180: character maps to <undefined>\n"
}
```

### Operating System

Windows 10 v21H2

### dbt version

dbt 1.2.2

### dbt Adapter

dbt-snowflake

### dbt Power User version

v0.7.9

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Could you retest with 0.8.1? Is this issue still present?

**Comment by thomasgjerdekog** [comment]
0.8.1 seems to have fixed it! Thanks :)
