### ISSUE TITLE
Errors after upgrading to 0.8.0 - python cmd window pops up and env_var no longer works. 

### ISSUE THREAD

**Issue by MurugR** [innoverio/vscode-dbt-power-user#179]
### Expected behavior

- Open VS Code
- Open dbt model file and wait for dbt version detection to finish. 
- Click on Execute dbt SQL play button and see results produced in tandem with dbt-osmosis. 

dbt-client                0.1.3                    pypi_0    pypi  
dbt-core                  1.3.0                    pypi_0    pypi  
dbt-extractor             0.4.1                    pypi_0    pypi  
dbt-osmosis               0.9.7                    pypi_0    pypi  
dbt-postgres              1.3.0                    pypi_0    pypi 

### Actual behavior

As stated at the end of https://github.com/innoverio/vscode-dbt-power-user/issues/130, extension version 0.8.0 has now stopped parsing environment variables. Now I'm getting a python window pop-up and error from the dbt Power User extension. Environment variable in the error message is in my settings.json file in the .vscode folder. 

### Steps To Reproduce

- Open VS Code
- Open dbt model file and wait for dbt version detection to finish. Error in screen capture, along with python cmd window, pops up at this point.  
- Continuing to click on Execute dbt SQL play button produces another error _"Could not execute query, because the Python bridge has not been initalized. If the issue persists, please open a Github issue"_. 

### Log output/Screenshots

![image](https://user-images.githubusercontent.com/80878454/198002856-be632db1-546a-4a2a-9fbf-89806b59fc85.png)

### Operating System

Windows 10

### dbt version

1.3.0

### dbt Adapter

dbt-postgres 1.3.0

### dbt Power User version

0.8.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Thanks I will take a look and see if I can fix it.

**Comment by mdesmet** [comment]
Can you try with 0.8.1.

I have fixed following issues:

- No detached window on Windows
- env vars present in python bridge
- path issue for query panel on Windows

Let me know how it goes.

**Comment by MurugR** [comment]
Looks good. Everything works as how it did prior to 0.8.0. No detached window, environment variables in dbt are resolving. 

![image](https://user-images.githubusercontent.com/80878454/198184119-2b79e6a5-d15d-48df-a19b-6e787f29f1f7.png)

**Comment by mdesmet** [comment]
Thanks for verifying!
