### ISSUE TITLE
Error: Node Type 'analysis' not implemented!

### ISSUE THREAD

**Issue by pedromachados** [innoverio/vscode-dbt-power-user#18]
I am getting this error on 0.22. 

I suppose it's because I have one SQL file in the `analysis` directory. 

I haven't had a chance to dig deeper into it but would be happy to if needed.

**Comment by ShaoYuan-Weng** [comment]
Hi @pedromachados,

Thank you for your feedback. Actually we don't use the analysis feature that's why we missed it... We are fixing the bug now :)

**Comment by mdesmet** [comment]
@pedromachados : Can you confirm this is working now in 0.2.4 and close this issue?

**Comment by pedromachados** [comment]
This issue has bee resolved in 0.2.4. Thank you!
