### ISSUE TITLE
Profiles Dir Override setting doesn't seem to work

### ISSUE THREAD

**Issue by bdee10** [innoverio/vscode-dbt-power-user#183]
### Expected behavior

I want to use the Profiles Dir Override setting to override the --profiles-dir parameter.

### Actual behavior

I set our override in the settings, but it doesn't seem to do anything

### Steps To Reproduce

Go to plugin settings, change the profiles dir override setting.

### Log output/Screenshots

![image](https://user-images.githubusercontent.com/116819371/198307170-e4aac4da-7a1b-4ddd-85bb-00b4034d418e.png)
![image](https://user-images.githubusercontent.com/116819371/198307219-37400a1f-351a-4206-af6a-650766371447.png)

### Operating System

macOS Monterey 12.6.1

### dbt version

1.0.3

### dbt Adapter

dbt-bigquery

### dbt Power User version

0.8.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Fixed in 0.8.2

**Comment by bdee10** [comment]
Works like a charm!

**Comment by dweaver33** [comment]
For anyone coming in here with the same issue, make sure your profile directory does not end with a `/` character.  

* Good: `/Users/home/myuser/.dbt`
* Bad: `/Users/home/myuser/.dbt/`
