### ISSUE TITLE
"Compiled dbt preview" seems not work

### ISSUE THREAD

**Issue by kaisp84** [innoverio/vscode-dbt-power-user#184]
### Expected behavior

When I click on "Compiled dbt preview" dbt compiles the opened model file and shows the compile output in a new window.

### Actual behavior

When I open a model file in VS code and press on "Compiled dbt preview" nothing happens. No hint for any errors is visible. It simply doesn't open the preview window. For example "Run dbt model" works as expected.

### Steps To Reproduce

Function never works for me.

### Operating System

Windows 10 Version 21H2 (OS Build 19044.2130

### dbt version

Core:   - installed: 1.3.0      - latest:    1.3.0 - Up to date!  Plugins:   - sqlserver: 1.3.0 - Up to date!

### dbt Adapter

dbt-sqlserver

### dbt Power User version

0.8.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
There should be an error if the Python process can't be started.

**Comment by telliott27** [comment]
I had a similar problem on 0.8.4: clicking the preview button would do nothing and a few seconds later an error would pop up about not being able to start the Python bridge. I installed 0.8.3 instead and the compiled dbt preview now works.

**Comment by mdesmet** [comment]
There should be another error before that indicates why the python process couldn’t be started. Please provide that error.

**Comment by mdesmet** [comment]
Closing as not reproducible. If you have more details, feel free to reopen it.

**Comment by kaisp84** [comment]
I searched in the extension logs folder and found this error message. Does this help?

2022-11-09 08:50:41.363 [error] Error: cannot open query-preview:/c%3A/Development/gpc/dbt/dbt-demo-sqlserver/models/dimensions/DM_D_CostType.sql. Detail: Unable to resolve text model content for resource query-preview:/c%3A/Development/gpc/dbt/dbt-demo-sqlserver/models/dimensions/DM_D_CostType.sql
    at a.$tryOpenDocument (vscode-file://vscode-app/c:/Program%20Files/Microsoft%20VS%20Code/resources/app/out/vs/workbench/workbench.desktop.main.js:2779:76347)
    at process.processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by mdesmet** [comment]
This error message seems about the query preview feature and not about the compilation feature.

Can you record a video of the extension starting and the actions you perform to validate if things are working.

**Comment by kaisp84** [comment]
Here you are. I hope this helps.
https://user-images.githubusercontent.com/20833767/200820143-b7032f50-027e-4d6b-9e6d-043743cab8ed.mp4

**Comment by mdesmet** [comment]
I don't think you are running the latest version. There shouldn't be a console window popping up. Can you verify that?

**Comment by kaisp84** [comment]
I'm running 0.8.6. Details below

VS Code Version:

PS: > code --version
1.73.0
8fa188b2b301d36553cbc9ce1b0a146ccb93351f
x64

Extension Versions:

PS: > code --list-extensions --show-versions     
dorzey.vscode-sqlfluff@0.1.9
innoverio.vscode-dbt-power-user@0.8.6
ms-python.isort@2022.4.0
ms-python.python@2022.18.1
ms-python.vscode-pylance@2022.11.10
ms-toolsai.jupyter@2022.9.1202862440
ms-toolsai.jupyter-keymap@1.0.0
ms-toolsai.jupyter-renderers@1.0.12
ms-toolsai.vscode-jupyter-cell-tags@0.1.6
ms-toolsai.vscode-jupyter-slideshow@0.1.5
ms-vscode.powershell@2022.10.0
samuelcolvin.jinjahtml@0.19.0

Python version:

PS: > python --version 
Python 3.10.8

**Comment by mdesmet** [comment]
Fixed in 0.8.7

What's weird is that you still get the console window. I actually tested that on windows and was able to let it dissapear by making it a daemon process. Could you try to get some process information about that Python console window?

**Comment by kaisp84** [comment]
Version 0.8.7 fixed the issue. Now preview is working again. Thanks!

And here the info about the python processes. Actually two processes are started because I am using a virtual environment. I piped process info to the attached python.json.txt file. 

PS: > Get-Process python | select -Property * -ExcludeProperty Parent, Modules, Threads | ConvertTo-Json -Depth 5 | Out-File python.json.txt

[python.json.txt](https://github.com/innoverio/vscode-dbt-power-user/files/9972955/python.json.txt)

Can it be related to the fact that I am running on Windows and in my workspace settings.json is set to "dbt.dbtPythonPathOverride": "../dbt-env-sqlserver-stable/Scripts/python.exe" ?
For me the path in the prompt title looks a little weired because it is mixed with / and \

**Comment by mdesmet** [comment]
Could you try selecting the python environment with ctrl shift p -- select python interpreter and remove the dbt.dbtPythonPathOverride?

**Comment by kaisp84** [comment]
That worked. 
I removed dbt.dbtPythonPathOverride from my workspace settings and and selected the interpreter with ctrl shipt p. When I entered the path manually and browsed for the interpreter I needed to make sure to select pythonw.exe instead of python.exe. 
When I selected the recommend python it worked also.

**Comment by mdesmet** [comment]
Yes but do you still get the popup console window?

**Comment by mdesmet** [comment]
https://stackoverflow.com/questions/9705982/pythonw-exe-or-python-exe

Ok that explains it. Thx for helping to investigate!
