### ISSUE TITLE
Opens dozens of python shells that do not close (25 dbt projects in a vscode work space)

### ISSUE THREAD

**Issue by jeff-skoldberg-ct** [innoverio/vscode-dbt-power-user#187]
### Expected behavior

vs code launches, power user launches normally.

### Actual behavior

When I launch vs code, the dbt power user add-in is launching dozens of python shells, bring my computer to a crawl.  This is new behavior.

### Steps To Reproduce

Open vs code.

### Log output/Screenshots

<img width="219" alt="image" src="https://user-images.githubusercontent.com/117289676/199545821-4e9dae07-d83d-4de5-b165-19f30ce57f81.png">

### Operating System

Windows

### dbt version

1.3

### dbt Adapter

snowflake

### dbt Power User version

0.8.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
The extension opens a python process per discovered project (it does a findInFiles in all your workspaces for dbt_project.yml). Could you perform such a search and tell how many files you find?

Is there anything particular about your setup? Do you use any packages? is this happening with every project you open?

**Comment by jeff-skoldberg-ct** [comment]
Hi @mdesmet, I think your answer helped me.  I have Airbyte installed locally, and it is added as a folder in my vs code workspace.  Within the Airbyte directory, there are 25 dbt_project.yml files.
I have removed Airbyte from my workspace, and now I get 3 python.exe launching.  
1) Are they supposed to stay up forever? 
2) all of them are launching the same interpreter, the one that is default for my workspace.  Similar to the screen shot in the original post, the part I blacked out is all the same folder path.  Is that expected?

**Comment by mdesmet** [comment]
Yeah this processes act as servers and keep the dbt manifest in memory to ensure speedy listing, compiling and execution. They use indeed the project interpreter as that's defining the Python environment where to find dbt.

**Comment by jeff-skoldberg-ct** [comment]
thanks, I will close this bug!

**Comment by mdesmet** [comment]
FYI I added a warning when more than 10 projects are found.
