### ISSUE TITLE
Query Results: x rows in y seconds, y never stops counting up after results have been returned

### ISSUE THREAD

**Issue by jeff-skoldberg-ct** [innoverio/vscode-dbt-power-user#188]
### Expected behavior

It should tell you how long the query took

### Actual behavior

it never stops counting up.  Here is an example of a query the returned in less than 1 second, but the wheel is still spinning and the counter is still counting:
<img width="212" alt="image" src="https://user-images.githubusercontent.com/117289676/199735787-cbc0bda7-8fc6-4d8b-befc-16b3b4158395.png">

### Steps To Reproduce

CTRL Enter on a SQL file

### Operating System

Windows

### dbt version

1.3

### dbt Adapter

snowflake

### dbt Power User version

0.8.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by jeff-skoldberg-ct** [comment]
It also looks like the "Dispatched SQL" tab is now missing.  Commenting on the same bug because I'm it is likely related to whatever update was released.

**Comment by mdesmet** [comment]
I can't reproduce the issue. Also latest version did not change anything related to query execution.

Could you check Help > Toggle developer tools and see if there is anything interesting being logged in the console?

**Comment by jeff-skoldberg-ct** [comment]
does this tell you anything?
<img width="379" alt="image" src="https://user-images.githubusercontent.com/117289676/199779508-c13414ad-e76d-4252-a240-839e6210c87c.png">

**Comment by mdesmet** [comment]
Must be something related to the query template. Maybe check if you have modified the queryTemplate, that shouldn't be required for snowflake.

**Comment by jeff-skoldberg-ct** [comment]
I have not modified anything.  :(

**Comment by mdesmet** [comment]
Can you post the executed query from the snowflake query log, maybe that will give some indication what went wrong?

**Comment by jeff-skoldberg-ct** [comment]
Further troubleshooting steps that did not work:
- uninstalled all other plugins related to dbt.
- removed all folders from the workspace except for one.

**Comment by jeff-skoldberg-ct** [comment]
Here is an example.  First screenshot in vs code.  Then screenshot from snowflake query history.
<img width="720" alt="image" src="https://user-images.githubusercontent.com/117289676/199789232-24845032-b893-4b7d-9899-79cdd38a3142.png">


<img width="270" alt="image" src="https://user-images.githubusercontent.com/117289676/199789440-ebc8d60f-02ba-4e60-a597-9fd836e10ba2.png">

**Comment by mdesmet** [comment]
Just to be sure can you verify following setting?

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/9265503/199792576-3b747125-121f-47ba-bd50-27d5d84b1f3b.png">

**Comment by jeff-skoldberg-ct** [comment]
yep, mine is the same as yours

<img width="591" alt="image" src="https://user-images.githubusercontent.com/117289676/199803990-3441cdeb-5f9d-4d78-a07d-b0c42970ef74.png">

**Comment by mdesmet** [comment]
Fixed in 0.8.4. I actually just suck up the exception as it is not crucial.

Let me know if it works for you

**Comment by jeff-skoldberg-ct** [comment]
yes, it seems to be fixed.  Back to normal!
