### ISSUE TITLE
Improve Autocomplete trigger for model names

### ISSUE THREAD

**Issue by juanbfactored** [innoverio/vscode-dbt-power-user#197]
### Expected behavior

whenever I type `{{ ref() }}` there should be list of suggestions showing all the models in my project.

### Actual behavior

There is no suggestion list and pressing `ctrl + space` does not show any of the models in the project.

### Steps To Reproduce

- Create a .sql file
- In the from clause type `{{ ref() }}`
- Press `ctrll + space`
- The list of suggestions does not contain any models from the project

### Log output/Screenshots

![image](https://user-images.githubusercontent.com/87039490/201221984-5b0ac0e4-f28a-42d1-a3ce-1c045bf92eeb.png)

### Operating System

macOS Monterrey (Intel)

### dbt version

1.3.0

### dbt Adapter

Snowflake

### dbt Power User version

0.8.7

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
The autocomplete is triggered by entering a quote.

This is actually something that can be improved.

**Comment by mdesmet** [comment]
Fixed in 0.8.8. Let me know if it works.
