### ISSUE TITLE
Ensure `dbt.pythonPathOverride` works with relative paths, tilde (Meltano)

### ISSUE THREAD

**Issue by mdesmet** [innoverio/vscode-dbt-power-user#199]
![image](https://user-images.githubusercontent.com/9265503/201538278-098a20b6-bb4b-4122-b1f3-b760e7131fd1.png)

**Comment by aaronsteers** [comment]
Related: I found that `${workspaceFolder}` also doesn't seem to work as expected in `dbt.profilesDirOverride` or `dbt.dbtPythonPathOverride`.

I worked around this by using `./...` in place of `${workspaceFolder}/...`.


https://code.visualstudio.com/docs/editor/variables-reference#_predefined-variables

**Comment by mdesmet** [comment]
> Variable substitution is supported inside some key and value strings in launch.json and tasks.json files using ${variableName} syntax.

Variable substitution is a common complaint in extensions. Currently vscode only does it in certain places and doesn't expose this feature.

If you are saying `.` and `..` work as expected we can close this issue. Could you also test `~`?

**Comment by aaronsteers** [comment]
> If you are saying `.` and `..` work as expected we can close this issue. Could you also test `~`?

I did not test `..` but I confirmed that `.` works as expected, in place of `${workspaceFolder}`

> Variable substitution is a common complaint in extensions. Currently vscode only does it in certain places and doesn't expose this feature.

Completely understandable. The VS Code docs are not super clear on this so as a user I was initially not sure what to expect. Your docs do have the caveat though about variables not being expanded, which I appreciate.
