### ISSUE TITLE
Extensions boots multiple out of process windows

### ISSUE THREAD

**Issue by reubster** [innoverio/vscode-dbt-power-user#200]
### Expected behavior

Extension works in an integrated manner

### Actual behavior

After upgrading to v0.9.0 and reloading vscode, I get an out of process python.exe window opened - one for each dbt project in my repo. 

### Steps To Reproduce

Happens with each launch of vscode in my dbt repo. 

### Log output/Screenshots

<img width="919" alt="image" src="https://user-images.githubusercontent.com/19515061/201620281-e9e1c202-c427-40f7-95dd-003a81f7e79f.png">

### Operating System

Windows 11

### dbt version

1.3.0

### dbt Adapter

snowflake

### dbt Power User version

0.9.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
How do you select the Python interpreter? Do you use the `dbt.dbtPythonPathOverride` setting or do you use the select python interpreter feature as explained in the README?

You should ensure to select the correct interpreter on Windows: See https://github.com/innoverio/vscode-dbt-power-user#select-the-python-interpreter-that-has-dbt-installed

See also: https://stackoverflow.com/questions/9705982/pythonw-exe-or-python-exe

**Comment by reubster** [comment]
It's the local python .venv interpreter. Not using the override. 

<img width="332" alt="image" src="https://user-images.githubusercontent.com/19515061/201649537-5a78b0d4-3987-409b-8c23-9b0edf2e1b6f.png">

**Comment by reubster** [comment]
I also have this problem. Can I get a compiled 0.8.9 ?

https://github.com/innoverio/vscode-dbt-power-user/discussions/191

**Comment by mdesmet** [comment]
0.9.2 should automatically select pythonw.exe if available. Let me know if that works.

**Comment by reubster** [comment]
@mdesmet - resolved! rtfm.
