### ISSUE TITLE
Cmd + T has been overriden by dbt

### ISSUE THREAD

**Issue by thomasaarholt** [innoverio/vscode-dbt-power-user#205]
### Expected behavior

Cmd + T should trigger the regular function/class/method lookup.

### Actual behavior

Since the latest release, when I press Cmd + T I get the following error:

![image](https://user-images.githubusercontent.com/2721423/201910269-0cd0d9bc-9ade-4c35-9f29-a3472d8de11c.png)

This is outside of a dbt environment, in this case in a python codebase.

### Steps To Reproduce

Press Cmd + T in VSCode.

### Operating System

Mac OS Ventura 13.0

### dbt version

1.0.3 - we are currently restricted to this

### dbt Adapter

snowflake

### dbt Power User version

v0.9.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Thanks for raising this. I will remove the shortcut.

**Comment by mdesmet** [comment]
Fixed in [0.9.3](https://github.com/innoverio/vscode-dbt-power-user/releases/tag/0.9.3)
