### ISSUE TITLE
Recurrence of An error occured while initializing the dbt project: Parsing Error Env var required but not provided

### ISSUE THREAD

**Issue by MurugR** [innoverio/vscode-dbt-power-user#207]
### Expected behavior

This is a recurrence of a portion of https://github.com/innoverio/vscode-dbt-power-user/issues/179. The dbt project now fails detection when VS Code is opened citing error described by screen capture in Comments section. 

I suspect the Python bridge is not picking up variables from the settings.json file again. 

### Actual behavior

dbt detect ends with error: 

### Steps To Reproduce

- Open VS Code
- Open dbt model file and wait for dbt version detection to finish. Error in screen capture pops up at this point.

### Operating System

Windows 10

### dbt version

1.3.0

### dbt Adapter

dbt-postgres 1.3.0

### dbt Power User version

0.9.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by MurugR** [comment]
![image](https://user-images.githubusercontent.com/80878454/202325799-1cf00916-48ae-4a54-bf19-5ab008d2bb20.png)

**Comment by mdesmet** [comment]
Can you remind me where and how this env var is set?

As long as you are setting the Python environment as explained in https://github.com/innoverio/vscode-dbt-power-user#select-the-python-interpreter-that-has-dbt-installed

It should take over all the environment variables that are set from the process and vscode.

**Comment by MurugR** [comment]
The environment variables are in my settings.json file inside the .vscode folder. This folder is in the workspace folder. 

When I downgrade back to 0.8.8 of dbt Power User, it works again. The fix was first applied on 0.8.1 then regressed a few versions after. 

![image](https://user-images.githubusercontent.com/80878454/202400174-a9e01e36-43bd-42c6-8d0f-787a83ee2448.png)
![image](https://user-images.githubusercontent.com/80878454/202400235-b2b5f11b-5825-4984-abaa-cf66417bf21a.png)

**Comment by mdesmet** [comment]
Ok is see what you mean. The Python extension doesn't pick up the terminal env vars as they are probably part of the core vscode api. What we currently support is the following: https://code.visualstudio.com/docs/python/environments#_environment-variables.

The goal is to actually being able to understand vscode variables.  The old code was kind of a hack. I will investigate it if I can get somehow also the terminal env vars. If not i will reactivate the old code again. 

I will make a release later today.

**Comment by MurugR** [comment]
Thanks and much appreciated. Your latest comment made me test a workaround. 

- Add an .env file named shared.env (can be any name with .env extension) into .vscode folder and place environment variables required by dbt in this file. Do not remove any entries in settings.json. 
- Add the following line in settings.json: `"python.envFile": "${workspaceFolder}/.vscode/shared.env"`

This worked. I can now use the latest dbt Power User extension without issues. I need to maintain certain environment variables in 2 places (shared.env and settings.json) but this is not an issue. Small effort to keep sensitive values hidden locally while allowing VS Code to pass variables to both Python and Integrated Terminals.

**Comment by mdesmet** [comment]
It's not ideal. I think the extension should work the same in the background as in the terminal. That's the goal, doesn't mean it's always easy :)

**Comment by mdesmet** [comment]
This seems to be supported in a nice way: https://github.com/microsoft/vscode/issues/46696

I will try to implement it like that.

**Comment by mdesmet** [comment]
Fixed 0.9.6. 

Unfortunately the above support is not exactly what we want. I restored the old behaviour but in combination with the envFile support (new in 0.9.5)

**Comment by MurugR** [comment]
Thanks - it worked. I'm still maintaining the workaround as Pytest in VS Code can't read settings.json file as well. 

![image](https://user-images.githubusercontent.com/80878454/202658780-0fa013a0-3c99-4e45-8f1c-5a7180e02788.png)

**Comment by mdesmet** [comment]
Cool, I will update the README with all this as well.
