### ISSUE TITLE
Modified regex for matching ref and source

### ISSUE THREAD

**Issue by camfrout** [innoverio/vscode-dbt-power-user#21]
Hi!

As part of my current dbt project, we are leveraging quite a few macros in our models. It seems that the current regex to match ref and source functions is currently not working when combined with macros in specific cases.

For example, we are using code like `{{ get_current_record(ref('my_table'), 'my_column','load_ts') }}`

With the current regex of `/(ref)[^}]*/` it returns the value `ref('my_table'), 'my_column','load_ts') ` which is not matching any real model and prevents the hyperlink to show.

My suggestion would be to change:
IS_REF to: `/(ref)\([^)]*\)/`
IS_SOURCE to: `/(source)\([^)]*\)/`

What it does is that for ref, the regex looks for the word `ref` directly followed by `(` and then stops at the first `)`.

**Comment by mdesmet** [comment]
Thanks @camfrout , will do some testing and will be arriving soon on your nearby computer screens!

**Comment by mdesmet** [comment]
Hi @camfrout, can you confirm if this is now working for you? It has been released in 0.2.4, If so you may close the issue.

**Comment by camfrout** [comment]
I can't test with `source` yet as 0.15.2 doesn't load sources in `manifest.json` the same way but it is working for `ref`. I will close this one. Thanks for the modification in the source code!
