### ISSUE TITLE
Bug: warning message uses same path twice: `project located in (path) that is contained inside another project (same path)`

### ISSUE THREAD

**Issue by aaronsteers** [innoverio/vscode-dbt-power-user#211]
I've been trying to get dbt Power User working in my container. This is a new one - not sure what this means or what to try next.

> dbt Power User detected a project located in file:///workspaces/meltano-demo-in-a-box that is contained inside another project file:///workspaces/meltano-demo-in-a-box. This is an unsupported configuration. If you believe this is a valid configuration, please open a github issue.

Any ideas/suggestions?

Update: Found the issue and created #212

**Comment by aaronsteers** [comment]
Looks like a simple bug in the error message. New PR at #211 should clarify the paths. 🤞

**Comment by aaronsteers** [comment]
After diving into the code I was able to find the _underlying_ issue that led me to the warning message. For curious: I 'moved' the `meltano.yml` file to the base directory but inadvertantly undid the 'delete' operation in git. Hence, I had two copied of the file in the old and new locations.)


I'll update the title of this issue to focus on the warning message improvement, since that is probably still worth updating.

**Comment by aaronsteers** [comment]
Follow up question for my own understanding: Should dbt Power User be able to find dbt projects that are not at the root? I haven't gotten this working as of yet, but it could have been due to other factors. 

Much of the code I was reviewing seems to imply that the `dbt_project.yml` file would be discovered in subfolders if not at root, but I couldn't get it working. Is it expected that this would be discovered if stored at (for instance) `./transform/dbt_project.yml`), or not yet?

**Comment by mdesmet** [comment]
Yeah it is expected. For example my vscode workspace is pointed at `workspace_root` and I have 2 projects there as in:

```
workspace_root/dbt_demo1
workspace_root/dbt_demo2
```

**Comment by aaronsteers** [comment]
> Yeah it is expected. For example my vscode workspace is pointed at `workspace_root` and I have 2 projects there as in:
> 
> ```
> workspace_root/dbt_demo1
> workspace_root/dbt_demo2
> ```

Thanks! I'll keep trying then. 😅

**Comment by thomasaarholt** [comment]
I see your PR in #212 was merged. We're still seeing similar messages for our repo that contains two projects:
- repo/snowflake
- repo/snowflake_restricted

I believe [this line](https://github.com/innoverio/vscode-dbt-power-user/blob/967d3b84afaf6c24e652262feb40381a3cf65524/src/manifest/dbtWorkspaceFolder.ts#L59) causes the extension to incorrectly infer that `snowflake_restricted` is inside `snowflake`. It should instead be comparing `snowflake_restricted` with `snowflake/` (forward slash at the end).

I'm not versed in js/ts at all. @aaronsteers any chance you would like to take a stab at this? 😅
