### ISSUE TITLE
vscode variables and relative paths don't work for profile dir override

### ISSUE THREAD

**Issue by juls858** [innoverio/vscode-dbt-power-user#237]
### Expected behavior
doesn't work:
 - using ${workspaceFolder} should allow extension to function properly
 - relative path `./`
works:
- hard coding the absolute path work

### Actual behavior

An error occured while initializing the dbt project: Runtime Error
  Could not find profile named 'ethereum'

### Steps To Reproduce

1. update profiles dir override value to `${workspaceFolder}`
1. reload window
2. open dbt model

### Log output/Screenshots

![image](https://user-images.githubusercontent.com/14811322/204906950-5c480e5d-c653-4949-bdfb-818e698f1154.png)

VSCode Version

> Version: 1.73.1 (Universal)
> Commit: 6261075646f055b99068d3688932416f2346dd3b
> Date: 2022-11-09T02:08:38.961Z (3 wks ago)
> Electron: 19.0.17
> Chromium: 102.0.5005.167
> Node.js: 16.14.2
> V8: 10.2.154.15-electron.0
> OS: Darwin x64 22.1.0
> Sandboxed: No

### Operating System

macOS 13.0.1 (22A400)

### dbt version

1.3.1

### dbt Adapter

snowflake

### dbt Power User version

v0.10.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Vscode doesn't provide the variables substitution logic as an API and there is no reliable library for parsing them.

If I remember correctly putting just a `.` works. I think you can't put a `/` at the end. See https://docs.getdbt.com/docs/get-started/connection-profiles#2-use-the-dbt_profiles_dir-environment-variable-to-change-the-default-location

**Comment by mdesmet** [comment]
I did add support for `${workspaceFolder}` in 0.10.3.

Please reopen the issue if you have any issues.

**Comment by aa-matthias** [comment]
Hi @mdesmet - it is still not working here having a workspace/project config like this:

```yml
    "terminal.integrated.env.windows": {
        "DBT_PROFILES_DIR": "./.dbt"
    },
```

moving the .dbt folder to ~ solved the problem so it looks like the DBT_PROFILES_DIR variable is not read correctly.
