### ISSUE TITLE
Activity bar continuously runs after query preview is returned

### ISSUE THREAD

**Issue by jnoynaert** [innoverio/vscode-dbt-power-user#241]
### Describe the feature

The progress bar along the top of the bottom panel continues to "run"/animate after query results are returned. This is very distracting when reading the table.

![image](https://user-images.githubusercontent.com/5920864/205004306-5cf17d3c-199a-43c2-a813-360f646c54f2.png)

Not sure if this is a bug or an enhancement request 🙂

**Comment by mdesmet** [comment]
This is rather a bug. I also seen this but haven't found why this is happening yet.

**Comment by geo909** [comment]
It would be really nice if somebody could fix this.. Admittedly this is a minor issue but, personally speaking, it can be extremely distracting while coding.

**Comment by mbkupfer** [comment]
For what it's worth, a helpful contributor on the dbt slack community mentioned a workaround that was successful for me.
1. go to commands: `Ctrl/Cmd + Shift + P` then select: Developer: Reload Window.

![image](https://github.com/innoverio/vscode-dbt-power-user/assets/6313008/fba5e919-3d9e-49e9-9a6f-45b159158236)

Worked like a charm.

**Comment by mdesmet** [comment]
@jlpjavi : are you still working on this?
