### ISSUE TITLE
Cannot find DBT resources

### ISSUE THREAD

**Issue by trallarn** [innoverio/vscode-dbt-power-user#28]
Hi and thanks for an interesting extension!

I've just installed it and run into the following problem:

Use case:
Open a folder containing a DBT project in vscode
-> Open a DBT model from the explorer
-> Click any of the models populated in the DBT POWER USER sidebar
-> Yields unable to open file message according to screenshot below

<img width="457" alt="Screenshot 2020-09-21 at 15 01 42" src="https://user-images.githubusercontent.com/535469/93769685-737b5300-fc1b-11ea-82fd-0623c8710d92.png">

It seems like the extension is searching for the model in /app which seems wrong. I expect it to search relative to the folder I've opened in vscode.

**Comment by mdesmet** [comment]
Hi @trallarn,

I'm not sure where the /app folder is coming from? Maybe you have copied the project from someone else? Could you recompile your project by running 'dbt ls'?

We are using the root_path as in the manifest.json file within your target folder:

"unique_id": "model.ov_ho.oorsprong_studenten_examen_ata", "package_name": "ov_ho", **"root_path": "/home/mdesmet/Projects/ov-project-ho"**

**Comment by trallarn** [comment]
Hi @mdesmet 

I run dbt in a docker container with /app as project root. I didn't realise that the compiled resources was used. That explains where this is coming from.

Thanks for that clarification on how manifest.json is used. I will figure something out to resolve this.

**Comment by mdesmet** [comment]
I see three options: 

- either we tell the user to recompile because the project folder is not matching the manifest 
- either we swap the root folder with the project location (the user must have copied the folder)
- or we don't do anything

Any opinions on this? I'm tempted to either do the first or the last.

**Comment by trallarn** [comment]
Is it necessary to use the `root_path` at all? Cannot relative paths be used? If possible this would be my preferred choice.

If not:
#1 is informative but doesn't support running dbt in a container
#2 could be implemented as an override option. This is the option that actually resolves the issue when running dbt in a container and thus what I would prefer
#3 I think it at least would be nice with an an error message that indicates that the paths in the manifest.json doesn't match the file system

Perhaps adding the fact that manifest.json is used by the plugin could be added to the github README. 

Managing dbt with a container I think is a very good practice, so for this plugin to be able to support that is a good thing. When using a container I might not even have dbt installed on my local machine so recompiling then isn't an option.

**Comment by mdesmet** [comment]
I don't know if you know but you can run vscode with docker or a WSL2 enviroment. That's exactly how I run dbt, I don't even have dbt installed on my windows OS. So it is already supported now to run DBT in a container setup without any configuration neeeded for this extension. 

Please check the Remote extension within vscode: https://code.visualstudio.com/docs/remote/remote-overview

I think apart from how the extension works it might be useful to explain some of these more special scenarios in the readme.

**Comment by trallarn** [comment]
I wasn't aware of that @mdesmet . I will definitely look inte the plugin. Thanks!

**Comment by karimamd** [comment]
Hello, I am having the exact same issue and looking for an easy solution
is there an option to override where the extension is looking to be /dbt instead of /app/dbt ?
maybe something in a configuration file ?

**Comment by mdesmet** [comment]
Assuming you  are also using docker. The out of the box solution seems to me to use the remote plugin and run dbt in your docker container instead of the directory that is being mounted in docker. As I said the remote extension is really great, I use it every day!

**Comment by mdesmet** [comment]
We have added some links in the README with pointers on how to use the remote extension.

**Comment by trallarn** [comment]
Great. Thanks @mdesmet.
