### ISSUE TITLE
order by not working in query preview on dbt-trino projects

### ISSUE THREAD

**Issue by RobbertDM** [innoverio/vscode-dbt-power-user#290]
### Expected behavior

```
select * from {{ ref("some_other_model") }}
order by "timestamp" asc
```
outputs an ordered table in the `query results` tab.

### Actual behavior

```
select * from {{ ref("some_other_model") }}
order by "timestamp" asc
```
outputs an unordered table in the `query results` tab.
You can still click the arrows to sort manually yourself, but imo it's confusing to see a random order every time at execution, while `order by` is in the query.

### Steps To Reproduce

Execute any `order by` statement with the plugin

### Operating System

Ubuntu 22.04

### dbt version

1.3.2

### dbt Adapter

dbt-trino

### dbt Power User version

0.10.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
You can avoid this behaviour by changing `dbt.queryTemplate` into something like `{query} limit {limit}`. This however won't work if your query already contains a LIMIT clause.
