### ISSUE TITLE
Enable functionality for nested projects

### ISSUE THREAD

**Issue by smitsrr** [innoverio/vscode-dbt-power-user#294]
### Describe the feature

Currently the extension doesn't allow for nested projects. 
This is generally how our repo is organized:
```
repository/
.devcontainer
engineering_team/
	project_1/
		models/
		seeds/
		snapshots/
		dbt_project.yml
	project_2/
		models/
		seeds/
		snapshots/
                target/
		dbt_project.yml
dbt_packages/
models/
seeds/
snapshots/
dbt_project.yml
```

I would like the nested projects to also be able to navigate to the target folder, for instance. 

### Describe alternatives you've considered

not using the extension - current situation. 

### Who will benefit?

companies who have complicated repos they've inherited 

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
@smitsrr : I believe this is fixed by https://github.com/innoverio/vscode-dbt-power-user/commit/4811a14d28f5bda01ca98715eef98c662971c952, could you retest and reopen if necessary?
