### ISSUE TITLE
An error occured while initializing the dbt project: No module named 'dbt.contracts.graph.parsed'

### ISSUE THREAD

**Issue by luizs81** [innoverio/vscode-dbt-power-user#295]
### Expected behavior

No errors when opening a project in VS Code

### Actual behavior

The following message pops up after detecting dbt:
An error occured while initializing the dbt project: No module named 'dbt.contracts.graph.parsed'
![image](https://user-images.githubusercontent.com/644079/214766289-fc44fead-68f6-4284-8b31-e680f6494872.png)

### Steps To Reproduce

Closing and opening the VS Code

### Log output/Screenshots

![image](https://user-images.githubusercontent.com/644079/214765996-df6f1136-a066-4d92-8e9f-dfb59756fb33.png)

![image](https://user-images.githubusercontent.com/644079/214766076-2099976f-0f39-4feb-a66d-ae7b99407a4c.png)

### Operating System

Windows 10

### dbt version

1.4.1

### dbt Adapter

dbt-snowflake 1.4.0

### dbt Power User version

v0.10.3

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jlpjavi** [comment]
I think this could be related to your DBT version being `1.4.1`; try with a lower one until the extension is prepared for that.

**Comment by luizs81** [comment]
Thanks for suggesting that.
I could make it work downgrading `dbt` to `1.2.4`.
Although now dt-power-user gives me a warning that my dbt is outdated, it does work as expected.
