### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by jackyshan82** [innoverio/vscode-dbt-power-user#30]
hi 
I installed the extension with config but it does not seem work at all.. any help ?

**Comment by mdesmet** [comment]
The extension doesn't require any config, it should use the compiled files that dbt generates.

Without any further insight in your setup it would be difficult to give you any hints (Win-Linux-Mac?, Docker/WSL?).

**Comment by jackyshan82** [comment]
Thanks for you reply. sorry, I did not provide much details.

I am using Visual Studio Code and installed dbt power user extension in Win10.

I mean I associated  .sql files with the jinja-sql language by configuring in Preferences > Settings for configuration.
