### ISSUE TITLE
Go to schema file from current model

### ISSUE THREAD

**Issue by LePeti** [innoverio/vscode-dbt-power-user#300]
### Describe the feature

I'd love a command that would take me from the currently open (focused) dbt model to its corresponding schema file (.yml). Similarly to how I now navigate with the help of your extension from a model to it's compiled sql in the target folder.

### Describe alternatives you've considered

I think this is also possible using the 'eamodio.find-related' package and setting up a custom rule but it'd be great to do this using a single extension.

### Who will benefit?

I think jumping from model to its test/docs is a workflow everyone does who develops dbt models

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
There is already an issue for this. See #77

Check the discussion there for more pointers, if you need any assistance contact me on Dbt slack.
