### ISSUE TITLE
'RuntimeException' is not defined

### ISSUE THREAD

**Issue by vanfloris** [innoverio/vscode-dbt-power-user#302]
### Expected behavior

Execute a model, and show the resulting data.

### Actual behavior

If I execute the model the following error is given:
![Scherm­afbeelding 2023-02-03 om 10 39 05](https://user-images.githubusercontent.com/97532742/216566303-04f90718-31c0-4529-a89c-3fce81514233.png)

### Steps To Reproduce

Running the model works but when executing the model the error pops up. (this was done in a new development environment, so there aren't many hints to why this is going wrong now)

### Log output/Screenshots

{
  "code": -1,
  "message": "name 'RuntimeException' is not defined",
  "data": "\"Error: Traceback (most recent call last):\\n  File \\\"/Users/florisvanleeuwen/.vscode/extensions/innoverio.vscode-dbt-power-user-0.11.2/dist/dbt_integration.py\\\", line 436, in compile_sql\\n    node = self.compile_node(self.get_server_node(raw_sql, temp_node_id))\\n  File \\\"/Users/florisvanleeuwen/.vscode/extensions/innoverio.vscode-dbt-power-user-0.11.2/dist/dbt_integration.py\\\", line 370, in get_server_node\\n    sql_node = self.sql_parser.parse_remote(sql, node_name)\\n  File \\\"/Users/florisvanleeuwen/.vscode/extensions/innoverio.vscode-dbt-power-user-0.11.2/dist/dbt_integration.py\\\", line 275, in sql_parser\\n    self._sql_parser = SqlBlockParser(self.config, self.dbt, self.config)\\n  File \\\"/Users/florisvanleeuwen/.local/share/virtualenvs/dbt-aZlMfyd7/lib/python3.10/site-packages/dbt/parser/base.py\\\", line 105, in __init__\\n    self._update_node_database = RelationUpdate(\\n  File \\\"/Users/florisvanleeuwen/.local/share/virtualenvs/dbt-aZlMfyd7/lib/python3.10/site-packages/dbt/parser/base.py\\\", line 74, in __init__\\n    macro = manifest.find_generate_macro_by_name(\\nAttributeError: 'NoneType' object has no attribute 'find_generate_macro_by_name'\\n\\nDuring handling of the above exception, another exception occurred:\\n\\nTraceback (most recent call last):\\n  File \\\"/Users/florisvanleeuwen/.vscode/extensions/innoverio.vscode-dbt-power-user-0.11.2/dist/node_python_bridge.py\\\", line 104, in <module>\\n    value = eval(_compile(data['code'], '<input>', 'eval'), _locals)\\n  File \\\"<input>\\\", line 1, in <module>\\n  File \\\"/Users/florisvanleeuwen/.vscode/extensions/innoverio.vscode-dbt-power-user-0.11.2/dist/dbt_integration.py\\\", line 405, in execute_sql\\n    compilation_result = self.compile_sql(raw_sql)\\n  File \\\"/Users/florisvanleeuwen/.vscode/extensions/innoverio.vscode-dbt-power-user-0.11.2/dist/dbt_integration.py\\\", line 440, in compile_sql\\n    raise RuntimeException(str(e))\\nNameError: name 'RuntimeException' is not defined\\n\\n\\tat ChildProcess.onMessage (/Users/florisvanleeuwen/.vscode/extensions/innoverio.vscode-dbt-power-user-0.11.2/dist/extension.js:5540:184)\\n\\tat Object.onceWrapper (node:events:646:26)\\n\\tat ChildProcess.emit (node:events:526:28)\\n\\tat ChildProcess.emit (node:domain:475:12)\\n\\tat emit (node:internal/child_process:938:14)\\n\\tat process.processTicksAndRejections (node:internal/process/task_queues:84:21)\""
}

### Operating System

macOS

### dbt version

1.4.1

### dbt Adapter

Snowflake

### dbt Power User version

v0.11.2

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
It is already fixed in master. will be released shortly.

**Comment by vanfloris** [comment]
The plugin from master works! Thanks

**Comment by gary-beautypie** [comment]
Hey, also experiencing this issue, when is a release expected? thanks!

**Comment by mdesmet** [comment]
Fixed in 0.11.3
