### ISSUE TITLE
Issue with path of some files when running on Windows

### ISSUE THREAD

**Issue by camfrout** [innoverio/vscode-dbt-power-user#33]
I am currently using the extension on a laptop running Windows.

I ran into an issue where some of the files would not show the parent/children when other ones did. After a bit of debugging, it seems to be related to the fact that `document.uri.path` returns a string with the drive letter sometimes capital and sometimes not.

Some files were showing: `path: "/c:/Users/xxx/model1.sql"` when others are showing `path: "/C:/Users/xxx/model2.sql"` (in one case the C: drive is uppercase and in the other one it is lower case).

A quick fix for this use case might be to change the file `manifestContainer.ts` and use `fsPath` instead of `path`, while catering for both Unix and Windows file systems. Replacing
```
if (currentFilePath.path.startsWith(projectRootUri.path + "/"))
```
by 
```
if (currentFilePath.fsPath.startsWith(projectRootUri.fsPath + "/") || currentFilePath.fsPath.startsWith(projectRootUri.fsPath + "\\"))
```

Happy to submit a PR if it's OK

**Comment by mdesmet** [comment]
We refactored the code quite a bit. You could help us in testing the PR.

Thanks for raising the issue!

**Comment by camfrout** [comment]
Hi. I just did a quick test with the new version in the PR and the models are showing correctly, even for the files that are not working for me in the current version.
