### ISSUE TITLE
WSL: Execute DBT SQL results in Cannot read properties of undefined (reading 'webview')

### ISSUE THREAD

**Issue by rmbrich** [innoverio/vscode-dbt-power-user#333]
### Expected behavior

VS Code is connected to WSL: Ubuntu (WSL2), and DBT Power User extension is installed in WSL. Should be able to use all the features of the plugin including "Execute DBT SQL". 

### Actual behavior

Clicking "Execute DBT SQL" button results in a VS Code error popup with the message:
`Cannot read properties of undefined (reading 'webview')`

### Steps To Reproduce

Using the postgres DBT adapter, try to execute DBT SQL against WSL remote.

### Operating System

Windows host, Ubuntu WSL environment

### dbt version

1.3.2

### dbt Adapter

postgres

### dbt Power User version

0.11.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by paulfry-payroc** [comment]
my colleague is also seeing this issue on MacOS with dbt versions 1.3 & 1.4.

The remainder of my team use WSL & aren't having any issues 🤔

**Comment by lllong33** [comment]
similar exception !

dbt debug info: 
```
dbt version: 1.3.3
python version: 3.9.6
python path: C:\Users\admin\.dbt\dbt_impala_env\Scripts\python.exe
os info: Windows-10-10.0.22621-SP0
```

**Comment by felipe-curebase** [comment]
Same problem here on mac, latest dbt redshift adapter version

**Comment by mkoenings** [comment]
same error here, vscode on windows server, with dbt 1.3.1 / dbt-sqlserver. I saw it working well, however,  it stopped working at some point. Python 3.9.0
The whole panel "Query Results" does not show up anymore. (no,  it's not just hidden)  I tried reinstalling the extension, no luck.

**Comment by icemtel** [comment]
Same issue: Windows, git bash, bigquery. (dbt run or show compiled sql commands work correctly)

**Comment by icemtel** [comment]
Additional observation: if I run this on a query with a syntax error, then I get a database error. So query is actually sent to the database, and the problem likely happens afterwards when the query results are supposed to be shown.

**Comment by mdesmet** [comment]
So you also get the error `Cannot read properties of undefined (reading 'webview')`

**Comment by ward-resa** [comment]
I am also getting this error. 
**vscode**
`Version: 1.78.1 (Universal)`

dbt Power User `v0.130.0`

**dbt debug output**
```console
dbt version: 1.5.0
python version: 3.9.16
python path: /opt/homebrew/opt/python@3.9/bin/python3.9
os info: macOS-13.3.1-arm64-arm-64bit
```
The dbt show command works and returns records. I agree with @icemtel in that the error must occurring when trying to display the results with the webview package as the error is indicating.

This was working only three days ago. Something changed in the last few days to cause this error now. I am not certain what steps to perform to find the change or package that might have broken this extension.

**Comment by Luttik** [comment]
I'm having the same issue. I'm even willing to help, but I find it quite hard to get started reading the plugin with the very limited number of comments being available.

I might be completely mistaken, but it seems like `this._panel` is not being set in `ModelGraphViewPanel` since `ModelGraphViewPanel.resolveWebviewView(...)` is never called...

As far as I can tell, [this is the violating line](https://github.com/innoverio/vscode-dbt-power-user/blob/master/src/lineage_provider/modelGraphViewPanel.ts#L115).

**Comment by nicogelders** [comment]
I'm having the same issue when running the plugin in code-server

**Comment by mar-pan** [comment]
Having the same on Cloud Workstations (Ubuntu) - aka dev Code workspace by GCP

**Comment by Luttik** [comment]
@mdesmet Hé This issue is closed but the bug is still present in the latest release.
