### ISSUE TITLE
flow editor that enables non tech savvy users to work with DBT

### ISSUE THREAD

**Issue by mdesmet** [innoverio/vscode-dbt-power-user#35]
Simlilar to https://documentation.matillion.com/docs/1991880

**Comment by rumbin** [comment]
In my eyes this would be far out of scope of this extension and dbt in itself.

**Comment by mdesmet** [comment]
It is one of the ideas that i had when originally creating this extension. It's not really about dbt but a layer on top of dbt, (dbt as execution engine).

it would require creating components for common SQL operations similar like what a product like Matillion does, and supporting different database engines. 

It would enable analysts to easily setup a flow, that can be converted to dbt code if necessary.

It's a huge effort, not impossible but indeed far out of scope.
