### ISSUE TITLE
Parent pane doesn't show direct ancestors but furthermost ones

### ISSUE THREAD

**Issue by dmorel** [innoverio/vscode-dbt-power-user#369]
### Expected behavior

I would expect the parent pane to show the **direct** parents and children of the current file.

### Actual behavior

it shows me the furthest ancestor (current model -> parent -> grandparent -> <shows only this one>)  I suspect it's just getting a list and picking up the first member. Works for children, not for parents. I think it's much more useful to show the direct parent.

### Steps To Reproduce

- open a model that has a parent and a grandparent
- see that the model in the PARENTS column on the pane is the grandparent, not the parent

### Operating System

MacOS 13.2.1

### dbt version

1.3.3

### dbt Adapter

dbt-snowflake

### dbt Power User version

0.16.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
I don't understand, AFAIK it shows the full chain of both children and parents of the currently selected model.

**Comment by mdesmet** [comment]
Closing as not actionable.

**Comment by dmorel** [comment]
here are 2 screenshots to illustrate:
- dbt docs
- vs code sidebar
you can easily see that what is in the sidebar is only the grandparents, not the parents

![CleanShot 2023-04-15 at 19 06 21](https://user-images.githubusercontent.com/54684/232241796-acdf69a8-b3a8-4e4e-bc12-4d2146acfb1f.png)

![CleanShot 2023-04-15 at 19 08 38](https://user-images.githubusercontent.com/54684/232241806-78f15353-1959-4b34-a0ac-656ef488781f.png)

**Comment by dmorel** [comment]
ok i get it, this is more of a UX issue: with the folding it looked like the direct parent was a folder of some sort, and the grandparent has a different icon, I didn't get it.
