### ISSUE TITLE
Formatting number of lines bug, processDiffOutput can not handle larger line numbers than original file

### ISSUE THREAD

**Issue by b-ned** [innoverio/vscode-dbt-power-user#372]
### Expected behavior

Formatting sql with `sqlfmt` through 'Format document with..'  should return formatted document
Input:
```
with
    source_data as (
        select 1 as col_1, 2 as col_2, 3 as col_3 union all select 3 as id_1, 4 as id_2, 2 as col_3
    )
select * from    source_data
```
Expected Output:
```
with
    source_data as (
        select 1 as col_1, 2 as col_2, 3 as col_3
        union all
        select 3 as id_1, 4 as id_2, 2 as col_3
    )
select *
from source_data

```

### Actual behavior

Input: 
```
with
    source_data as (
        select 1 as col_1, 2 as col_2, 3 as col_3 union all select 3 as id_1, 4 as id_2, 2 as col_3
    )
select * from    source_data
```
Formatting sql with `sqlfmt` through 'Format document with..' --> dbt Power User (dbtDocumentFormattingEditProvider) throws the following error:
![image](https://user-images.githubusercontent.com/74150550/225122303-108177fd-054f-4e44-a104-030cea75f535.png)

**Note:**
When adding empty lines in the input (up to 8 lines in total), the bug **does not appear**

Input :
```
with
    source_data as (
        select 1 as col_1, 2 as col_2, 3 as col_3 union all select 3 as id_1, 4 as id_2, 2 as col_3
    )
select * from    source_data



```

result: successfully formatted :

```
with
    source_data as (
        select 1 as col_1, 2 as col_2, 3 as col_3
        union all
        select 3 as id_1, 4 as id_2, 2 as col_3
    )
select *
from source_data

```

Running `sqlfmt` from command line works fine for both inputs.

### Steps To Reproduce

Format a SQL file from the 'Format Document with.. ' that will generate more lines than the current file has.

System:
dbt Power User :  0.11.6
sqlfmt : 0.17.0
VSCode :  1.76.1

### Log output/Screenshots

My first guess would be that `processDiffOutput` in  `dbtDocumentFormattingEditProvider` is not taking into account the extra lines that `sqlfmt` might generate. Hence the 'Illegal value for `line`' Error.

I have minimal experience with typescript, but I am happy to give it a go at resolving this bug,

### Operating System

Mac OSX 

### dbt version

1.4.2

### dbt Adapter

big-query

### dbt Power User version

0.11.6

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Hi @b-ned, please have a try to fix the issue! It is very easy to open the project in debug mode with your own dbt project and try to fix it.

<img width="441" alt="image" src="https://user-images.githubusercontent.com/9265503/225137244-91960c5b-d850-43c8-bcb9-0fb1f930da16.png">

**Comment by b-ned** [comment]
Hi @mdesmet , thanks for the explanation, I will give it a go.

**Comment by b-ned** [comment]
Hi @mdesmet,

I managed to solve the bug, by taking into account `document.lineCount` the parser. My forked branch: https://github.com/b-ned/vscode-dbt-power-user/tree/bugfix/formatting-lines-bug/src

I found another bug, during the testing of my changes (which is also present in the original master).
I solved this one in the same branch.


This second bug caused swapped lines at the end of a `diff chunk`.
**Example input:**
```
with
    cte_1 as (
        select 1 as col_1, 1 as col_2, 1 as col_3 union all select 2 as id_1, 2 as id_2, 2 as col_3
    ),  -- cte_1

    cte_2 as (
        select 3 as col_1, 3 as col_2, 3 as col_3
        union all
        select 4 as id_1, 4 as id_2, 4 as col_3
    ),  -- cte_2
    cte_3 as (
        select 5 as col_1, 5 as col_2, 5 as col_3
        union all
        select 6 as id_1, 6 as id_2, 6 as col_3
    ),  -- cte_3

select *
from cte_1
``` 

**Buggy Output:**
```
with
    cte_1 as (
        select 1 as col_1, 1 as col_2, 1 as col_3
        union all
        select 2 as id_1, 2 as id_2, 2 as col_3
    ),  -- cte_1

        select 3 as col_1, 3 as col_2, 3 as col_3
    cte_2 as (
        union all
        select 4 as id_1, 4 as id_2, 4 as col_3
    ),  -- cte_2
    cte_3 as (
        select 5 as col_1, 5 as col_2, 5 as col_3
        union all
        select 6 as id_1, 6 as id_2, 6 as col_3
    ),  -- cte_3

select *
from cte_1
```

Could you add me to the repo so I can submit a PR?
