### ISSUE TITLE
Add model documentation to DBT power user view

### ISSUE THREAD

**Issue by carlgronvald** [innoverio/vscode-dbt-power-user#380]
### Describe the feature

I think it would be useful to add the documentation of a model to the DBT power user panel view. 

### Describe alternatives you've considered

Documentation on model hover, #96 , could also provide some of the same benefits.

### Who will benefit?

Developers would be able to see documentation while working on a model. This has two functions:
1. Model documentation is more easily understood by developers
2. Because model documentation is shown while developing, there is more of an onus to keep the documentation up to date, as drift between the truth of the model and the documentation is immediately apparent.

### Are you willing to submit PR?

- [x] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
This seems very useful. Would you be able to provide a PR?
