### ISSUE TITLE
Bug: Errors generated for mono repo with similar dbt paths

### ISSUE THREAD

**Issue by ShaneMazur** [innoverio/vscode-dbt-power-user#381]
https://github.com/innoverio/vscode-dbt-power-user/blob/967d3b84afaf6c24e652262feb40381a3cf65524/src/manifest/dbtWorkspaceFolder.ts#L59-L61

This is causing issues because it doesn't just find when dbt projects are inside other dbt projects. It is also finding when dbt projects share a common path substring. 

For example, a mono-repo with the following 2 dbt project paths will generate this error but I think this is intended to be a supported pattern.

- `~/user/my_dbt_repo/dbt_project`
- `~/user/my_dbt_repo/dbt_project_spark`

**Comment by mdesmet** [comment]
Fixed in 0.12.1. Let me know if it works.
