### ISSUE TITLE
Extend generated model from source functionality

### ISSUE THREAD

**Issue by b-ned** [innoverio/vscode-dbt-power-user#388]
### Describe the feature

**Proposed features**
1. A settings field that allows the user to set the naming template for the generated model to align with their specific naming convention.
For example: `base__{schema}_{table_name}` or `stg_{table_name}`

2. Generate the model file in the same folder as where the `source.yml` is located. 

**Goal of features**
This eliminates having to rename and move the generated file each time.

### Who will benefit?

All users that generate base models from source.

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
These changes are welcome, maybe they can be configured through vscode configurations (can be set globally or per workspace).
