### ISSUE TITLE
Prevent terminal to be DBT terminal by default?

### ISSUE THREAD

**Issue by bastienboutonnet** [innoverio/vscode-dbt-power-user#40]
Just recently picked up the new release and now every time I start vscode the default terminal is "DBT" (btw dbt should not be capitalised according to their guidelines --minor comment). 

I wonder if there is a way to have this terminal not be activated or selected by default?

Alternatively an option to not run `dbt ls` at start up (#38 ) would work but it's a sad solution.

**Comment by mdesmet** [comment]
As far as I know the terminal is only selected when running models. When restarting vscode it just selects my default terminal (bash in my case).

**Comment by bastienboutonnet** [comment]
Hmmm, that's really strange...

Here's a quick screen recording.
When I launch vscode in a repo that has dbt the following happens:
1. activating extensions
2. Checking dbt installation
3. At this momennt the terminal switches to a DBT terminal

https://share.getcloudapp.com/7KublkGJ

That doesn't happen to you?

**Comment by mdesmet** [comment]
https://user-images.githubusercontent.com/9265503/104126439-d88abe00-535c-11eb-9b6d-5beafe801942.mp4

**Comment by bastienboutonnet** [comment]
Oh dear, I have no idea what could be causing this behaviour on my end then...

I'll have to do some digging... It definitely only happens on projects with where a dbt project is present. Don't know why though...

**Comment by bastienboutonnet** [comment]
I also just tried it with terminal closed. When I open a new session via `code .` in the project folder, when it's time for the extension to do it's thing it pops up a new terminal window.

I wonder if there is a setting that we might have different values for...

**Comment by bastienboutonnet** [comment]
And I just removed the extension and installed it again. Upon install it also kicks in a new terminal window.

Puzzling...

**Comment by mdesmet** [comment]
It seems that in your case when the terminal is being created it also gains focus. Is there any configuration that gives focus to a terminal when it's created?

Here we create the terminal, that's indeed when we run the version check.

https://github.com/innoverio/vscode-dbt-power-user/blob/4aefd2eaef435cba016feeb4ebd403c96f7b197f/src/dbt_client/dbtClient.ts#L80

Focus is only given when the focus is set to true for the command:

https://github.com/innoverio/vscode-dbt-power-user/blob/4aefd2eaef435cba016feeb4ebd403c96f7b197f/src/dbt_client/dbtClient.ts#L97

As you can see the version check doesn't have the focus property:
https://github.com/innoverio/vscode-dbt-power-user/blob/4aefd2eaef435cba016feeb4ebd403c96f7b197f/src/dbt_client/dbtCommandFactory.ts#L32

**Comment by bastienboutonnet** [comment]
There must be indeed but I cannot find it at all in any of my settings. It may be another extension that is causing this. Which is going to be quite annoying to find. I guess there is nothing you folks can do other than perhaps leaving it up to the user whether to do this so that they can do it on demand. Not sure if that's something you would consider. The setting could be off by default so that most people benefit from the auto startup in case they don't have a silly configuration as I have.

**Comment by mdesmet** [comment]
Hi @bastienboutonnet ,

I've added a flag to disable the automatic listing. But i prefer to keep the issue open until we better understand what's going on, or for other people to see.

Here is how to setup the flag:

![image](https://user-images.githubusercontent.com/9265503/105543689-615d0e80-5cfa-11eb-862f-0ad4bd346b11.png)

**Comment by bastienboutonnet** [comment]
@mdesmet makes sense yeah, I don't know if anyone is running into the same behaviour as me, but at least this option means I'll be able to not be constantly "annoyed" by the new terminal focus. Thanks a lot for looking into this!

**Comment by moltar** [comment]
I am running into the same thing and it is truly annoying. Every time I open VS Code or reload VS Code it pops the terminal view and dbt is always the one that gets focus.

I think the focus is probably just a race condition of terminals. Whichever one is ready first get focus. Just my guess.

But why does the terminal panel open in the first place?

**Comment by moltar** [comment]
Btw, `dbt.listModelsDisabled: true` does not solve this problem. :(

**Comment by mdesmet** [comment]
I have changed the implementation to use a OutputChannel and use only a pseudo terminal when running dbt commands that require focus (like model runs or tests).
