### ISSUE TITLE
dbt 1.5 support

### ISSUE THREAD

**Issue by mdesmet** [innoverio/vscode-dbt-power-user#402]
### Describe the feature

Ensure dbt 1.5 is supported

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by aksestok** [comment]
Ironically, the extension prompts you to upgrade to 1.5, but after upgrading the extension fails to load with this error message:

```
An error occured while initializing the dbt project: cannot import name 'DEFAULT_PROFILES_DIR' from 'dbt.flags' (<env-path>/lib/python3.11/site-packages/dbt/flags.py)
```

[Dagster](https://github.com/dagster-io/dagster) very recently implemented backward compatible support if that's any help or inspiration for whoever can pick it up: https://github.com/dagster-io/dagster/commit/d9f90875c66f443eb00a2d8977a5f2264c9793ce

**Comment by mdesmet** [comment]
I'm planning to tackle this during the weekend.

**Comment by smahin89** [comment]
Hello 👋  I just recently upgraded to 1.5 and faced this same issue. Is there any workaround or solution possible ?

**Comment by collin-austad** [comment]
Recently upgraded to 1.5 as well and seeing this: 
> An error occured while initializing the dbt project: No module named 'dbt.contracts.graph.parsed'

Seems like a related issue?
