### ISSUE TITLE
See resultset of model

### ISSUE THREAD

**Issue by mdesmet** [innoverio/vscode-dbt-power-user#41]

**Comment by Elektry-On** [comment]
Hi Michiel
Quickly wanted to ask whether this functionality is still planned. From our perspective this would add great benefit to the extension as this would be similar to the "Run Query" in dbt cloud I guess. This way we don't have to copy/paste the compiled code and execute it separately in another tool or browser tab.

I thought how to best approach this one and probably it would be possible for the extension to take the compiled code and call a dbt operation [dbt run-operation](https://docs.getdbt.com/reference/commands/run-operation) which uses the run_query macro [Run_Query Jinja Macro](https://docs.getdbt.com/reference/dbt-jinja-functions/run_query) to return the results. What do you think?

**Comment by mdesmet** [comment]
I also agree that this is the next priority for this plugin to become more productive with less context switching.

Ideally we would not rely on installing any user code into a dbt project itself.  I was thinking to create a custom task inheriting the internal dbt code. The disadvantage of this approach is that we don't rely on the public dbt api and experience might vary over different dbt versions.

The output should be displayed in a html table within vscode. Ideally the user would be able to modify the sql query to adapt for different test cases. Something like following plugin https://marketplace.visualstudio.com/items?itemName=koszti.snowflake-driver-for-sqltools

What do you think?

**Comment by Elektry-On** [comment]
I have played around with a macro that could be called like this:
`dbt run-operation get_results --args "sql: SELECT COUNT(*) FROM Table1""`

and the macro definition would look like:
`{% macro get_results(sql) %}

  {% set results = dbt_utils.get_query_results_as_dict(sql) %}
  {{ log(results, info=True) }}
  
  {% do return(results) %}
{% endmacro %}`

This would get the query results (as dict) in the console. But then again you made some very good points, as the extension should not rely on user defined macros. Additionally, having the output in a console window is just half the fun when having it as a html table would allow to filter/sort it 👍
Adapting/Changing the sql query on the fly would make perfect sense too. It would be cool to prevent another settings conf where I would have to enter the data warehouse credentials again. Do you think reusing them from the dbt project would be feasible?

**Comment by mdesmet** [comment]
I was thinking of following this approach:

Create a tasks similar to:
https://github.com/fishtown-analytics/dbt/blob/7ec5c122e17ab7e1a5dd1e1cab36527159564a0f/core/dbt/task/run_operation.py#L16

By doing this you can call all adapter methods (including running a query) and have access to the graph. In this task you could run whatever query and print it as a dict. so it can be picked up.

We can then call this task programmaticaly similar to how we run existing dbt commands.

https://github.com/innoverio/vscode-dbt-power-user/blob/5815cec7d4968dbc9b7ba7d07fef34cd3fffae85/src/dbt_client/dbtCommandFactory.ts#L105-L107

**Comment by Elektry-On** [comment]
I see, you want to dig deep down the rabbit hole 🐇😀

I see the powerfulness of the approach, on the other side directly interacting with the library would result in more maintenance overhead going forward I would assume. For example the performance improvement they did in 19.1 could probably had an impact and could maybe lead to multiple version of the run_operation to maintain. But this are just simple thoughts from a person that did not dive too deep into their library yet. 😉

If you think its feasible why not trying and see how it works out 👍

**Comment by Elektry-On** [comment]
I have seen that PopSQL did an integration with dbt: https://popsql.com/updates/dbt-integration which allows to execute the query during development. So this makes this issue even more important that we have that functionality as well in VSCode.

**Comment by Elektry-On** [comment]
Were you able to test this already?

**Comment by mdesmet** [comment]
Well, the querying works, but haven't put the time in displaying the results.

I currenlty use following plugin in vscode to bridge this gap:

https://marketplace.visualstudio.com/items?itemName=mtxr.sqltools

**Comment by mailtosumitrai** [comment]
Any updates on this one?

**Comment by kmclaugh** [comment]
Just wanted to note that this is great idea and when this added we'll switch from dbt cloud to using this extension in vscode

**Comment by rumbin** [comment]
related: #86

**Comment by mdesmet** [comment]
Implemented in latest version
