### ISSUE TITLE
More intuitive icons

### ISSUE THREAD

**Issue by djmikeale** [innoverio/vscode-dbt-power-user#410]
### Describe the feature

I find the icons could be improved to be more intuitive. I'm a new user, and always need to hover over the icons to be sure what is what:
![image](https://user-images.githubusercontent.com/104904492/233574294-ce4de07d-3012-4e2a-b64f-5d6ced4092ef.png)
furthermore, when running parent models or child models, the icon used is the same triangle/play button that's used for execute dbt SQL, rather than the database icon for run:
![image](https://user-images.githubusercontent.com/104904492/233574822-5ff7f48f-ef8b-43dc-ba5b-0b9d39423087.png)

![image](https://user-images.githubusercontent.com/104904492/233574870-dbc187bc-7260-4db4-bfe0-c9111fa4453f.png)

### Describe alternatives you've considered

Here's some emoji-suggestions that would be intuitive for me, but they should probably use some open-source vectors instead? (Not entirely sure how this space works)
- Execute dbt SQL and compile: the current icons are good
- Build dbt Model: 🛠️
- Run dbt Model: 🏃 or something like <img width="32" alt="image" src="https://user-images.githubusercontent.com/104904492/233576241-22ef06d5-51c7-4d54-b02f-3e03fe6946a3.png">
- Run dbt tests: e.g. 🧪 or <img width="32" alt="image" src="https://user-images.githubusercontent.com/38935692/233581371-9fc5768a-f70f-4475-93e5-8e8e4fed8d6d.png">

icon for running parent models or child models should prob be the same as "Run dbt Model"

### Who will benefit?

New users will more quickly be able to understand what the buttons do. (on the contrary existing users might be a bit confused to start with 🙃)

### Are you willing to submit PR?

I don't know how to change the code, but I'll happily look for the relevant icons, if I'm told what license terms are needed for the icons!

- [x] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Please provide a PR with both light and dark themed icons.

**Comment by djmikeale** [comment]
Nice! Do you know what size the icons should be? and what license terms are needed for this type of product? I'm hoping a cc by 3.0 license would work, but really idk

**Comment by mdesmet** [comment]
Just have a look at the existing images, they are specified in package.json. I'm not sure about the license, we can always revert back to the old icons if some issues arise.

**Comment by djmikeale** [comment]
Hi, I've created a local branch and made the necessary changes. I can't push it due to some permission issues to the repo, can you help? 
Also, how do I check whether the icons will look good in the extension?

**Comment by mdesmet** [comment]
you need to fork the repository and make a pull request.

To test you can simply launch the extension in debug mode:

<img width="290" alt="image" src="https://github.com/innoverio/vscode-dbt-power-user/assets/9265503/1f3910e2-0a04-4693-8610-345792ce2005">

**Comment by djmikeale** [comment]
Thanks, I'll try to do that :)On 15 May 2023, at 12.34, Michiel De Smet ***@***.***> wrote:﻿
you need to fork the repository and make a pull request.
To test you can simply launch the extension in debug mode:
