### ISSUE TITLE
Generate schema yml from model

### ISSUE THREAD

**Issue by b-ned** [innoverio/vscode-dbt-power-user#415]
### Describe the feature

Generate a schema yml from a sql model.

Functionality like [code-gen ; generate model yml](https://github.com/dbt-labs/dbt-codegen/tree/0.9.0/#generate_model_yaml-source)

Right click inside model file, generate model schema.yml. Output should be in same folder as model file.

Ideally implementing existing dbt code-gen macro instead of rewriting it inside extension code.

### Describe alternatives you've considered

Running the codegen macro and copy pasting the result into a yml file.

### Who will benefit?

All users

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Sorry I closed it by accident!

**Comment by b-ned** [comment]
Hi @mdesmet,

I managed to build a working prototype, by using the existing structure that executes dbt commands.
Note that you have to have the `dbt-labs/codegen` package installed, for this to work.

I built a function in `dbtProject.ts` that generates the YML.

```
  generateSchemaYML(modelPath: Uri, modelName: string) {
    const generateYMLCommand =
      this.dbtCommandFactory.createGenerateSchemaYMLCommand(
        this.projectRoot,
        this.dbtProfilesDir,
        modelName
      );
    this.dbtProjectContainer.addCommandToQueue(generateYMLCommand);
  }
```

The command is created as follows:

```
createGenerateSchemaYMLCommand(
    projectRoot: Uri,
    profilesDir: string,
    modelName: string
  ): DBTCommand {

    return {
      commandAsString: `dbt run-operation generate_model_yaml --args '{"model_names": ["${modelName}"]}'`,
      statusMessage: "Generating Schema YML",
      processExecutionParams: {
        cwd: projectRoot.fsPath,
        args: [
          "-c",
          this.dbtCommand([
            "'run-operation'",
            "'generate_model_yaml'",
            "'--args'",
            `'{"model_names": ["${modelName}"]}'`,
          ]),
        ],
      },
      focus: true,
    };
  }
```

As a result, it prints the yml file in the terminal:

```
20:03:27  Running with dbt=1.4.5
20:03:27  [WARNING]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
There are 1 unused configuration paths:
- models.example_project.example
20:03:27  version: 2

models:
  - name: base_seed
    description: ""
    columns:
      - name: id
        description: ""

      - name: first_name
        description: ""

      - name: last_name
        description: ""
```

To generate the YML file, I would like to catch the output that is being printed as logging in the terminal, 
any suggestions on how to best approach this?

**Comment by mdesmet** [comment]
Isn't this just calling adapter.get_columns_in_relation and then writing to a yaml file? I don't think we want to have a dependency on dbt-codegen.

**Comment by b-ned** [comment]
You're right, I will build a solution using the functions in the `dbt_integration.py`
