### ISSUE TITLE
DuckDB file lock when Execute dbt SQL Feature

### ISSUE THREAD

**Issue by xrafhue** [innoverio/vscode-dbt-power-user#435]
### Expected behavior

To have the option to close the connection after executing the query and to remove the lock on the DuckDB file.

### Actual behavior

I'm currently working on a DBT project that connects to a DuckDB database file. As you may know, the .duckdb file extension can only be opened by a single process at a time, unless in ReadOnly mode.

When I execute an SQL query in a model using the "Execute dbt SQL (Ctrl+Enter)" button, it opens the "QUERY RESULT" tab and displays the results, which is perfect! However, the connection to the database remains active and the .duckdb file is locked.

For now, I've been using the lsof command to identify the process that is using the file, and then killing it. After that, the "Execute dbt SQL" function no longer works, and I have to reload the workspace to use it again.

### Steps To Reproduce

- Set Dbt Profile with a Duckdb connection :
```
dbt_profile:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: "/path-to-duckdb-file/my-duckdb-database-file.duckdb') }}"
```
- Then Open an sql file to execute with dbt

- Then "Execute dbt SQL (Ctrl+Enter)"
![image](https://github.com/innoverio/vscode-dbt-power-user/assets/57148485/7c2eebdc-ae13-4f17-adc8-b43e66d559e8)

- See Result Query :
![image](https://github.com/innoverio/vscode-dbt-power-user/assets/57148485/f365d237-a20a-4e15-b030-f10a05045476)

After that there is not option to close the connection, so the duckdb file is locked.
![image](https://github.com/innoverio/vscode-dbt-power-user/assets/57148485/3ef94e7c-0f70-48c0-b60b-d40655953c78)

### Operating System

Debian GNU/Linux 11 (bullseye)

### dbt version

core: 1.5.0

### dbt Adapter

duckdb: 1.5.0

### dbt Power User version

v0.13.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by droher** [comment]
@xrafhue I believe this issue was resolved in 1.5.1: https://github.com/jwills/dbt-duckdb/issues/162
