### ISSUE TITLE
Support manual override of target-path

### ISSUE THREAD

**Issue by larspettermadsstuen** [innoverio/vscode-dbt-power-user#444]
### Describe the feature

In our repo we would like to use jinja in our `target-path`, but this is not supported by the extension, as described in [this issue](https://github.com/innoverio/vscode-dbt-power-user/issues/189).

If the extension supported a manual override of target-path (i.e. an textbox that lets you optionally specify which folder the extension should use as `target-path`), we would be able to keep jinja code in `target-path`.

### Who will benefit?

Those who use jinja code in target-path. This is particularly useful when you have a large repo with long parse times, to keep a separate target-path for each target - so you avoid a full reparse everytime you switch target. According to [dbt](https://www.getdbt.com/blog/analytics-engineering-next-step-forwards/#:~:text=Complexity%20in%20the%20dbt%20ecosystem), a big (and growing) share of dbt deployments have a large number of models.

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Sounds doable, maybe you can give it a try. It shouldn't be that big of a change.

- You would need to provide a setting in package.json
- You would need to look wherever we look for the target path that it takes that setting

We already use this way of working in other places so simply doing something similar should work.
