### ISSUE TITLE
git checkout other project in same workspace will cause dbt vscode trigger update

### ISSUE THREAD

**Issue by jesse23** [innoverio/vscode-dbt-power-user#46]
## Step

- Load a workspace with dbt project and other project.
- Debug and run some module.
- Git checkout non dbt project, just for switching a branch.

## Result
- Looks like dbt vscode plugin will retrigger the task? I check the dbt log output and see that behavior...
- A task terminal will be launched without any content.

**Comment by mdesmet** [comment]
you mean the model listing is triggered when you add a new project in the same workspace, even if it's not a dbt project? It should indeed listen for any changes in the models folder and list models when anything changes. Can you confirm it's this process you are talking about?

FYI: There is a debounce on that event in order for it to not trigger too much exactly for this type of changes (git checkout or change branch)

**Comment by jesse23** [comment]
I am not sure it is related to `dbt ls` or not....Step about is how I could reproduce the issue at my local.

Today for ur comments I tried to re-install it and test it again to see if I can find more clues for help - I find another simple step to reproduce it: by just reload the window, it will create a dummy task terminal...no new print in the output.
![image](https://user-images.githubusercontent.com/643912/105638160-3203ea00-5e3f-11eb-88fc-2ca1ccd0332b.png)

**Comment by mdesmet** [comment]
You seem to have the same issue as @bastienboutonnet where the terminal is taking focus when it shouldn't (at creation time). Anyway as long as there's no output, it's not actually doing something, but I understand it's a bit annoying. I'll look into it again to see if I can find something.

**Comment by mdesmet** [comment]
The implementation has changed regarding this feature. Please reopen if you think this issue still occurs
