### ISSUE TITLE
Error occurred while initialising dbt project while using pre-release dbt version

### ISSUE THREAD

**Issue by dietofworms** [innoverio/vscode-dbt-power-user#460]
### Expected behavior

I would expect the extension to work with pre-release versions.

### Actual behavior

It returns an error message:

>An error occured while initializing the dbt project: invalid literal for int() with base 10: '0b4'

Here is the output from `dbt --version`:

```
Core:
  - installed: 1.6.0-b4
  - latest:    1.5.1    - Ahead of latest version!

Plugins:
  - snowflake: 1.6.0b3 - Ahead of latest version!
```

### Steps To Reproduce

* install a pre-release version of `dbt-snowflake`
* try to use dbt power user extension in vs code

### Log output/Screenshots

```
An error occured while initializing the dbt project: invalid literal for int() with base 10: '0b4'
```

### Operating System

macOS

### dbt version

1.6.0-b4

### dbt Adapter

dbt-snowflake

### dbt Power User version

v0.13.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
Fixed in https://github.com/innoverio/vscode-dbt-power-user/commit/a6d055c9e751cc15872759842da1ee585b83bcf4
