### ISSUE TITLE
An error occured while initializing the dbt project: cannot import name 'DEFAULT_PROFILES_DIR' from 'dbt.flags'

### ISSUE THREAD

**Issue by Nevermetyou65** [innoverio/vscode-dbt-power-user#463]
### Expected behavior

There should be no error

### Actual behavior

- The error notification appear every time I restart vscode
- Can not use `query result` tab. there is another error `Could not execute query, because the Python bridge has not been initalized. If the issue persists, please open a Github issue.`

### Steps To Reproduce

- Every time I open the vscode
- I am sure that I selected env that contains dbt package

### Log output/Screenshots

![image](https://github.com/innoverio/vscode-dbt-power-user/assets/67499630/e42c80c3-d9b7-433e-a3fd-7a0e459df946)

### Operating System

Ubuntu 20.04.5 LTS

### dbt version

1.5.1

### dbt Adapter

dbt-postgres

### dbt Power User version

0.13.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by yunruuuc** [comment]
Got same bug under same dbt version and dbt-snowflake adapter

**Comment by mdesmet** [comment]
You are not on the latest version of dbt power user so it is not compatible with dbt 1.5.

**Comment by Nevermetyou65** [comment]
@mdesmet Thank for the replying. But how can I ret the latest version? I believe the version shown in vscode extension is v0.11.4 which is not the latest right? the latest should be v0.14.0
