### ISSUE TITLE
Run results feature not working in dbt 0.19

### ISSUE THREAD

**Issue by nirakon** [innoverio/vscode-dbt-power-user#47]
Using conda enviroment with dbt installation from git.

Constantly "detecting dbt" with no result.
![image](https://user-images.githubusercontent.com/43750521/106258305-b3d48880-622e-11eb-8f79-2b7458bf93ed.png)

It's working fine with powershell.

What am I doing wrong?

**Comment by mdesmet** [comment]
what do you mean by "dbt installation from git"? The code is only tested with installation through pip and official dbt releases.

**Comment by nirakon** [comment]
Installed it from source as in https://docs.getdbt.com/dbt-cli/installation/#install-from-source

I had an error with snowflake plugin when installing from pip.

So I removed dbt-snowflake from requirements cause I don't need it anyway

**Comment by mdesmet** [comment]
What's the output if you run dbt --version in powershell?

**Comment by nirakon** [comment]
![image](https://user-images.githubusercontent.com/43750521/106267690-116ed200-623b-11eb-848a-ccd6c3ddd621.png)

**Comment by mdesmet** [comment]
So I'm just guessing here. The plugin offered you to install dbt for you but you selected no?

I see that you activate manually the conda environment, which means that vscode is not aware about your conda environment. This is the pointer, you need to select the correct python environment. See https://code.visualstudio.com/docs/languages/python#_environments

**Comment by nirakon** [comment]
I've found the problem.

I tried to install with pip again and discovered that some dependencies not compatible with Python 3.9.1 (and when I create new enviroments using conda it's by default instaling 3.9.1) so I downgraded python to 3.8.5 and installed dbt using pip successfully, then changed the interpreter and extension works fine.

**Comment by nirakon** [comment]
Hmm, sorry for false positive. Seems like a lot of features still not working for me. I'm wondering where's the root of the problems could be, maybe because I'm using conda?

**See the compiled SQL and the run status in the statusbar** - Not working
![image](https://user-images.githubusercontent.com/43750521/106452152-8e4ab780-6498-11eb-8597-977cdafe9b4c.png)

**See the model graph** - Not working
![image](https://user-images.githubusercontent.com/43750521/106452323-c3efa080-6498-11eb-9533-d0df4000d3d8.png)

**Go to definition** - Not working (Tried with CTRL as well)

**Comment by rudeb0y** [comment]
Same issues
- no "go to definition"
- the graph is always empty

**Comment by mdesmet** [comment]
As I'm always running in remote (ubuntu) and sometimes forget all features on windows, I just did some tests using windows but no issues here with current version. 

Any errors in the console log (Help -> Toggle Developer tools)?

**Comment by nirakon** [comment]
Yeah, it has

[-1612206308562.log](https://github.com/innoverio/vscode-dbt-power-user/files/5906131/-1612206308562.log)

**Comment by mdesmet** [comment]
Thanks, that helped, the run results artifacts seems to have slightly changed in the newest dbt version. I will come up with a fix soon. will keep you posted!

**Comment by mdesmet** [comment]
We have released a new version (0.4.8). For now the run results status won't work in latest version, however it should not impact the other features as model graph or clickthrough. We will need to support different versions of the artifacts.

Let me know if it works.

**Comment by nirakon** [comment]
My appreciation to you for such a fast fix!

Model graph -- Working
Go to definition -- Working
Autocompletion -- Working

**Comment by mdesmet** [comment]
Thanks! If the extension brings you value, please rate or review it on https://marketplace.visualstudio.com/items?itemName=innoverio.vscode-dbt-power-user.
