### ISSUE TITLE
Project inside a project

### ISSUE THREAD

**Issue by ofek1weiss** [innoverio/vscode-dbt-power-user#471]
### Expected behavior

Hello

I am developing a dbt package, and have another dbt package inside of it for tests.
When i try to use dbt power user, i get the following error message:
```
dbt Power User detected a project located in /Users/ofek/workspace/dbt-data-reliability/integration_tests that is contained inside another project /Users/ofek/workspace/dbt-data-reliability. This is an unsupported configuration. If you believe this is a valid configuration, please open a github issue.
```

The weird thing is, when i look at the source code, it seems that support for this configuration was added a few months ago - [see here](https://github.com/innoverio/vscode-dbt-power-user/commit/9d758acfb3d80cfb9a779faa3ce04e130251e9c6), and the string for my warning does not exist anymore in the project.

I installed the latest version of the extension (0.13.0), am i doing something wrong

### Actual behavior

getting the error message as described above.

### Steps To Reproduce

cloning [this repo](https://github.com/elementary-data/dbt-data-reliability) and using dbt power user version `0.13.0`

### Log output/Screenshots

![image](https://github.com/innoverio/vscode-dbt-power-user/assets/55920061/90f1cef8-19e8-4138-b842-785bbc8d9030)

### Operating System

MacOS 13.4.1

### dbt version

1.5.4

### dbt Adapter

postgres

### dbt Power User version

0.13.0

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by mdesmet** [comment]
As you said this seems not to be anymore present in the latest version. Please reopen if you find this is still an issue.
