### ISSUE TITLE
Models not shown in the dropdowns

### ISSUE THREAD

**Issue by analyzequicker** [innoverio/vscode-dbt-power-user#476]
@mdesmet First off, this extensions looks very promising and I hope you continue to support it. I have been an avid DBT user and just starting to use vscode more. I'm facing the same issue mentioned below where the extensions capability seems to work except for the left hand pane (Python 3.9.2, DBT 1.5.2, DBT Bigquery 1.5.3). For example, I can execute the parent models play button successfully, but the models are not showing up. Any help would be greatly appreciated! Thanks.

Jason

### Discussed in https://github.com/innoverio/vscode-dbt-power-user/discussions/293

<div type='discussions-op-text'>

<sup>Originally posted by **michael-pyne** January 24, 2023</sup>
Hi. 

I am trying to figure out how to get my models shown in the drop-downs on the left here. Does anyone know what I am doing wrong? Everything else works (query previews etc.) 

<img width="354" alt="image" src="https://user-images.githubusercontent.com/123483857/214344817-a229d131-191c-4236-808a-1515c40a42be.png">
</div>

**Comment by mdesmet** [comment]
Is it possible to create a demonstration project using eg. postgres database or figure out what is the difference between a working project and a non-working project?

**Comment by analyzequicker** [comment]
@mdesmet - it ended up just being a misunderstanding of how the extension works. Models ended up showing up in the left pane once I added ref statements to other models. Also, I didn't realize models could be ran by right clicking and selecting run dbt model.
