### ISSUE TITLE
Feature request: setting for or detection of dbt installed via homebrew

### ISSUE THREAD

**Issue by ElRico** [innoverio/vscode-dbt-power-user#48]
Homebrew is the [recommended method](https://docs.getdbt.com/dbt-cli/installation/) to install dbt on macOS. However homebrew creates a separate Python environment specific to dbt (in /usr/local/Cellar/dbt). That is why the extension is showing dbt as not installed in VS Code.

It would be great to have an extension setting to either specify the path the dbt bin or the dbt Python environment. Better still would be automatic detection of homebrews dbt installations.

**Comment by mdesmet** [comment]
Hi @ElRico, I think this is already supported. See https://code.visualstudio.com/docs/languages/python#_environments

**Comment by ElRico** [comment]
Yep, I am using that setting currently in the workspace settings of my dbt projects. However, I think it would be good to make the detection automatic, because I think a number of users will not know where the dbt Python environment lives. It is also the same environment across all workspaces, but setting it globally would clash with other Python workspaces (where we don't want to use the dbt environment). That is why from my perspective an extension specific way to set the Python environment/path to the dbt binary would be a great addition and then ideally detect homebrews installation automatically and set it accordingly.

**Comment by mdesmet** [comment]
Thanks for your feature suggestion, however as I don't have a mac, it's something I can't support for now.
