### ISSUE TITLE
Plugin fails to install DBT

### ISSUE THREAD

**Issue by povorozniuk** [innoverio/vscode-dbt-power-user#49]
I had dbt installed using homebrew. After adding this plugin to visual studio code, the VS code started complaining that there is no dbt installed in 3.9 python env.
I clicked Yes to the question if I want it installed; however, at some point in the process it got stuck (see screenshot below)

![image](https://user-images.githubusercontent.com/29631366/106958252-b89dae80-66fe-11eb-8c64-4a30e98aad5d.png)

I waited for 20 min to no avail.

macOS: Catalina

**Comment by mdesmet** [comment]
I think dbt is currently not working on python 3.9. We don't parse the output of the installation command. If the installation fails, than obviously dbt won't be detected.
