### ISSUE TITLE
Allow to configure whether compiled or run SQL should be shown

### ISSUE THREAD

**Issue by infused-kim** [innoverio/vscode-dbt-power-user#50]
Hi,

First of all, thank you for creating this amazing extension!

It would be great if we could configure whether we want to see the `compiled` or the `run` SQL. I rarely care about the `run` SQL that contains all the table creation code.

Usually I run my model and it has some kind of error and I need to debug it by manually running the compiled code.

So it would be really great if we could configure which type of model we want to see.

And it would also be great if you could add `dbt Power User: Show run SQL` and `dbt Power User: Show compiled SQL` to the command palette.

**Comment by mdesmet** [comment]
Hi Kim, that's a great idea. 

I think i will drop the current run results status bar feature and replace it with these two commands. I might also add buttons on the model editor if I can find some good icons.

The run results feature is broken since 0.19. #47

**Comment by mdesmet** [comment]
Hi Kim:

I added two commands as displayed here:

![image](https://user-images.githubusercontent.com/9265503/109432705-cf3cda00-7a0c-11eb-9945-fd11048ca6d7.png)

Let me know if that resolves your issue. I haven't added any UI for now. If you like it, please rate the extension on https://marketplace.visualstudio.com/items?itemName=innoverio.vscode-dbt-power-user

**Comment by infused-kim** [comment]
Amazing, thank you so much.

I have posted a review and mentioned your extension on the DBT forums:
https://discourse.getdbt.com/t/how-we-set-up-our-computers-for-working-on-dbt-projects/243/16

**Comment by mdesmet** [comment]
Thanks a lot, if you have any other ideas, please submit an issue!
