### ISSUE TITLE
Could not find profile named ...

### ISSUE THREAD

**Issue by jsnb-devoted** [innoverio/vscode-dbt-power-user#507]
### Expected behavior

I'm just getting started with the plug in and I haven't been able to get the profile to load properly yet. I'd expect that this setting:
```
  "terminal.integrated.env.linux": {
    "DBT_PROFILES_DIR": "${workspaceFolder}/data/dbt/profile/",
  },
```
would be enough to make some progress loading the extension.

### Actual behavior

Every time I reload the window I get the `Could not find profile name...` error. The extension host output has a slew of `TypeError: Cannot read properties of undefined (reading 'webview')` errors but that seems unrelated.

### Steps To Reproduce

I'm developing on a remote host with a project with 1500+ models. We work in a monorepo so the dbt project is not in the top level directory. I install the extension and add the `DBT_PROFILES_DIR` env variable via `terminal.integrated.env.linux` in my workspace settings file. When I reload the workspace the dbt project is detected (I can see it in the status bar), my python executable with dbt is installed and I get the `Could not find profile named...` error. 

If I copy the profile to my default location `~/.dbt` then extension gets a little further and errors on some other environment variables that I don't have set yet. It indicates to me that the `DBT_PROFILES_DIR` variable doesn't seem to be working.

### Log output/Screenshots

![Screenshot 2023-08-04 at 10 50 13 AM](https://github.com/innoverio/vscode-dbt-power-user/assets/79863718/385bf811-7ec2-422f-b337-cfbe4a5792bd)
![Screenshot 2023-08-04 at 10 50 34 AM](https://github.com/innoverio/vscode-dbt-power-user/assets/79863718/9f45e4c9-8d7a-4401-a809-17e4d3a9ca04)
![Screenshot 2023-08-04 at 10 50 36 AM](https://github.com/innoverio/vscode-dbt-power-user/assets/79863718/04bbb73b-1533-4f83-afe4-ec5d883be0bb)

### Operating System

Ubuntu 20.04.6 LTS (Focal Fossa)

### dbt version

1.5.4

### dbt Adapter

snowflake 1.5.2

### dbt Power User version

v0.15.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

**Comment by jsnb-devoted** [comment]
I found a log line in the developer tools that at least explicitly says that it is using the `~/.dbt` directory:
![Screenshot 2023-08-04 at 12 38 27 PM](https://github.com/innoverio/vscode-dbt-power-user/assets/79863718/a7b79cef-00be-43c7-b5f1-1f141b98d9b5)

**Comment by jsnb-devoted** [comment]
I was grepping around the code and found the `profilesDirOverride`. I got past it by setting: `"dbt.profilesDirOverride": "${workspaceFolder}/data/dbt/profile" ` in my settings.

![Screenshot 2023-08-04 at 12 47 34 PM](https://github.com/innoverio/vscode-dbt-power-user/assets/79863718/7a4f2acb-0d86-44c2-baf8-d157f2353b83)

Not sure how far that will get me.

**Comment by jsnb-devoted** [comment]
Made a little more progress. The next issue is that our dbt_project has jinja in the `target-path`. The extension doesn't render the jinja so it tries to open the manifest at: `my/workspace/path/{{ my_var }}`

**Comment by mdesmet** [comment]
Fixed by https://github.com/innoverio/vscode-dbt-power-user/commit/b787599e54289bcea6f0950c4029e41d0df99c19

**Comment by laumc98** [comment]
Hello, I'm having the same issue
