### ISSUE TITLE
VSCode Extension not working

### ISSUE THREAD

**Issue by GenDemo** [innoverio/vscode-dbt-power-user#52]
Hi

I would like to use your VSCode extension, but it doesn't seem to work. When ever I click the run arrow in the top right, I get this error.
We are now on dbt v19, but even before upgrading, I got this error. Is there something I need to set up?

![image](https://user-images.githubusercontent.com/58798533/108654229-532e2800-751c-11eb-8b14-bc6c4e23e6f4.png)

Also, when I click on the 'ref' in a file to jump to the file being referenced, I get this popup:

![image](https://user-images.githubusercontent.com/58798533/108654406-b7e98280-751c-11eb-864e-8da0b41a5df6.png)

I would really appreciate your help.

**Comment by GenDemo** [comment]
Sorry wanted to tag/label this as a question, but I can't seem to be able to do that.

**Comment by mdesmet** [comment]
I'm guessing you run your dbt in docker? You should investigate how to setup the vscode plugin, that way all paths will be correctly resolved (including your dbt profile).

https://code.visualstudio.com/docs/remote/remote-overview

**Comment by GenDemo** [comment]
This was an issue before I started using docker.
But that doesn’t help - there is nothing to set up, don’t you just install the extension?

Kind Regards,

Andries van Wyk
Sent from Outlook<https://aka.ms/qtex0l> for iOS
________________________________

**Comment by GenDemo** [comment]
yeah that didnt help at all.

**Comment by reubster** [comment]
Hi @GenDemo 

Just thought I should comment on this. The error message you post above is saying that;

... a default target environment cannot be found 
... for the profile 
... that is configured in the dbt_profiles.yml 
... that has been found in the project folder by the dbt-power-user extension. 

The dbt-power-user extension can only pick up a default target env as there is no opportunity to pass it variables.  

Not sure how familiar you are with dbt, but some things I would check if I was experiencing this would be; 
- is there a virtualenv activated on vscode launch?
- what profile is configured in dbt_profiles.yml  
- which profiles.yml is in use / where is it? 
- is a default target env set? 
- set the DBT_PROFILES_DIR environment variable?

**Comment by HakimIndriawan-BNPA** [comment]
Hi, is there any updates on this? I'm having a simillar issu myself :(
