### ISSUE TITLE
Generate documentation YAML gives connection is closed error

### ISSUE THREAD

**Issue by ppradnesh** [innoverio/vscode-dbt-power-user#532]
### Expected behavior

1. I cloned three dbt projects from this list - jaffle_shop, attribution_playbook, mrr_playbook
2. When I try to generate documentation, it works okay for attribution_playbook, but I get connection_closed
![Screen Shot 2023-08-20 at 3 00 44 PM](https://github.com/innoverio/vscode-dbt-power-user/assets/20821587/5e1ae073-39c4-4b37-92ec-4bd6bcda0731)
 error for other two dbt projects

### Actual behavior

Generate documentation for all the projects

### Steps To Reproduce

I use python 3.11, dbt 1.6 and latest extension version

### Operating System

mac os

### dbt version

1.6

### dbt Adapter

snowflake

### dbt Power User version

1.6

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by anandgupta42** [comment]
This should have been fixed in the latest release. Closing it for now.
