### ISSUE TITLE
Documentation editor: error on saving documentation

### ISSUE THREAD

**Issue by sandhein** [innoverio/vscode-dbt-power-user#556]
### Expected behavior

In the jaffle-shop project I updated some documentation in the new documentation editor and clicked the "Save documentation" button to save the newly edited fields to the yml file located in the same folder:

### Actual behavior

An error occured with the following error-Message:
Could not save documentation to \c:\Users\XNLXD03x\projects\jaffle_shop-main\models\staging\schema.yml: Error: ENOENT: no such file or directory, open '\c:\Users\XNLXD03x\projects\jaffle_shop-main\models\staging\schema.yml'
### Steps To Reproduce

Run the jaffle-shop project on a Windows Server, edit the documentation in the documentation editor and click Save.

### Log output/Screenshots

![grafik](https://github.com/innoverio/vscode-dbt-power-user/assets/26199754/aff545fe-966c-41e3-9d53-c558094018c7)

Output from Developer Tools:
![grafik](https://github.com/innoverio/vscode-dbt-power-user/assets/26199754/dee45410-6a42-47b6-b3b4-ca8eed09670f)

### Operating System

Windows Server 2019

### dbt version

1.6.1

### dbt Adapter

dbt-oracle

### dbt Power User version

0.17.3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

Any thoughts on what is going on here and how I might get around this issue?
Appreciate any help with this in advance!

**Comment by mdesmet** [comment]
Fixed by https://github.com/innoverio/vscode-dbt-power-user/commit/bc345513b87e7de57b115f8317d0b390eae7c51f

**Comment by anandgupta42** [comment]
@sandhein New version with the fix has been release. Please make sure you update the extension to 0.17.4

**Comment by anandgupta42** [comment]
@sandhein circling back on this, please let us know if this is still an issue.

**Comment by anandgupta42** [comment]
I am closing this issue for now. Please re-open if the problem persists.

**Comment by sandhein** [comment]
@anandgupta42: Thank you for the fix, works perfectly now:-).
Sorry for the late answer, I have been in holiday a couple of days.
