### ISSUE TITLE
Execute DBT SQL results in Cannot read properties of undefined (reading 'webview')

### ISSUE THREAD

**Issue by Luttik** [innoverio/vscode-dbt-power-user#570]
### Expected behavior

VS Code should provide a preview of the data

### Actual behavior

The followin message is displayed:
> Encountered an unknown issue: Cannot read properties of undefined (reading 'webview'). If the issue persists, please seek help in our dbt Community Slack channel #tools-dbt-power-user or report it on GitHub.

### Steps To Reproduce

I just run any script.  This has been an issue for me for over half a year even though I've kept the extension up to date.

### Log output/Screenshots

```
[error] TypeError: Cannot read properties of undefined (reading 'webview')
    at QueryResultPanel_1.<anonymous> (c:\Users\dtlut\.vscode\extensions\innoverio.vscode-dbt-power-user-0.17.5\dist\extension.js:31316:25)
    at Generator.next (<anonymous>)
    at c:\Users\dtlut\.vscode\extensions\innoverio.vscode-dbt-power-user-0.17.5\dist\extension.js:31501:68
    at new Promise (<anonymous>)
    at Module.__awaiter (c:\Users\dtlut\.vscode\extensions\innoverio.vscode-dbt-power-user-0.17.5\dist\extension.js:31480:12)
    at QueryResultPanel_1.transmitError (c:\Users\dtlut\.vscode\extensions\innoverio.vscode-dbt-power-user-0.17.5\dist\extension.js:31315:21)
    at QueryResultPanel_1.<anonymous> (c:\Users\dtlut\.vscode\extensions\innoverio.vscode-dbt-power-user-0.17.5\dist\extension.js:31381:19)
    at Generator.throw (<anonymous>)
    at rejected (c:\Users\dtlut\.vscode\extensions\innoverio.vscode-dbt-power-user-0.17.5\dist\extension.js:31490:28)
```

### Operating System

Windows 11

### dbt version

This seems to be an issue for every dbt-version

### dbt Adapter

and it seems to be an issue for every dbt-adapter

### dbt Power User version

 0.17.5

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

**Comment by Luttik** [comment]
There was an issue before about the same but. But it as marked as resolved without actually being resolved. And not reopened after I asked it to. This is a pretty vital component to the plugin so I think it should be adressed.

**Comment by mdesmet** [comment]
It should be addressed. We found some issues that were resolved that also resulted in the same error.

It looks like there is a promise rejection but we don't know which promise it was. These errors are listed on the extension page. Maybe you could copy paste those here. That would help us in debugging.

<img width="1051" alt="image" src="https://github.com/innoverio/vscode-dbt-power-user/assets/9265503/255d17fd-56dc-440c-8be6-6d43468bb45f">

**Comment by Luttik** [comment]
Hi @mdesmet, thanks for the quick response!

In the runtime status tab that you show, all I see is the Uncaught Error `Cannot read properties of undefined (reading 'webview')`. I don't know if that's helpful for you? If I can help by checking something else, I will be glad to help.

**Comment by mdesmet** [comment]
@Luttik ： I contacted you on dbt Slack to setup a call.

**Comment by Luttik** [comment]
Thanks, @mdesmet for the fix on master!
