### ISSUE TITLE
Support dots in model names

### ISSUE THREAD

**Issue by monti-python** [innoverio/vscode-dbt-power-user#61]
In our project we use dots in model names to support multiple schemas. We are using this solution to extract schema name and alias from the node name -> https://discourse.getdbt.com/t/extracting-schema-and-model-names-from-the-filename/575

I created a PR to support this (#60)

**Comment by mdesmet** [comment]
Thanks a lot for your PR, this has been released now (v0.5.2). let me know if it works for you!

If you get value from this extension please rate the extension on https://marketplace.visualstudio.com/items?itemName=innoverio.vscode-dbt-power-user

**Comment by monti-python** [comment]
Thank you @mdesmet for the extension and for merging the PR! It's working well 👍
