### ISSUE TITLE
Extension does not work with 2 dbt projects in the same workspace

### ISSUE THREAD

**Issue by Elektry-On** [innoverio/vscode-dbt-power-user#62]
Hi All!

My workspace structure is as follows:
![image](https://user-images.githubusercontent.com/62945720/114211208-a2130e00-9960-11eb-8153-276c6d77881d.png)

While the extension works properly in the first project ("DBTTransform"):
![image](https://user-images.githubusercontent.com/62945720/114211650-2ebdcc00-9961-11eb-88e6-418ce031f489.png)

It seems to not work in the second project ("DBTTransform_Synapse"):
![image](https://user-images.githubusercontent.com/62945720/114211606-22397380-9961-11eb-8c92-43206adc5e06.png)

Extension installed version: v0.5.1
DBT installed version: 0.19.0

Otherwise it's a great extension, thanks a lot for the hard work!
Sven

**Comment by Elektry-On** [comment]
Looking at the Tasks - dbt output console it looks like it does both 2 dbt list commands for both projects.

**Comment by Elektry-On** [comment]
I tested different orderings of the folder paths in the code-workspace settings with an interesting outcome. If I move the "DBTTransform_Synapse" folder at the first position and the "DBTTransform" at second position like this:
![image](https://user-images.githubusercontent.com/62945720/114213118-e9020300-9962-11eb-83b2-f312df8fd08b.png)
It does work.

With this ordering:
![image](https://user-images.githubusercontent.com/62945720/114213312-1b136500-9963-11eb-9eaf-8279b6f84ca6.png)
It does NOT work

**Comment by mdesmet** [comment]
That's interesting. Could you setup a project that i can reproduce the issue?

**Comment by Elektry-On** [comment]
This should do. You should see the extension working in the first project but not in the second.
[PowerDBT.zip](https://github.com/innoverio/vscode-dbt-power-user/files/6289635/PowerDBT.zip)

**Comment by mdesmet** [comment]
Thanks, I've found the error and fixed it in v0.5.2. Let me know if it works now!

If you get value from this extension please rate the extension on https://marketplace.visualstudio.com/items?itemName=innoverio.vscode-dbt-power-user

**Comment by Elektry-On** [comment]
I tested it with version 0.5.2 and it worked. Thanks a lot for the quick support!
