### ISSUE TITLE
Extension fails to activate

### ISSUE THREAD

**Issue by callumwebb** [innoverio/vscode-dbt-power-user#66]
Hi there, firstly thanks for your work on this extension, it's made me significantly more productive which is why I'm sad it recently broke in my environment!

The extension fails to activate, so all functionality is borked. Here's a dump from the VS Code developer tools console:
```
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1917 Overwriting grammar scope name to file mapping for scope source.sql.
Old grammar file: file:///Applications/Visual%20Studio%20Code.app/Contents/Resources/app/extensions/sql/syntaxes/sql.tmLanguage.json.
New grammar file: file:///Users/callum/.vscode/extensions/ms-mssql.mssql-1.10.1/syntaxes/SQL.plist
register @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1917
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62 [Extension Host] (node:19985) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
m @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:62
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1904 Activating extension 'innoverio.vscode-dbt-power-user' failed: r.replace is not a function.
_logMessageInConsole @ /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.desktop.main.js:1904
```

And my platform:
```
Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z (1 wk ago)
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 19.6.0
```

I'm running dbt `0.19.1`. Please let me know if I can share any extra information.

**Comment by mdesmet** [comment]
I'm also on 0.19.1 but no issues here. Could you try to downgrade the version of the extension and check if you experience the same with v0.5.1?

![image](https://user-images.githubusercontent.com/9265503/115541883-ed51e880-a29f-11eb-9b0e-ff9f9511c6a1.png)

**Comment by OHDMax** [comment]
I've got the exact same problem (r.replace is not a function) but on a Windows machine and with a fresh install of Python 3.8, dbt 0.19.1 and vscode 1.55.1. Downgrading did not help. Is there any information I can provide to help debug this issue further?

**Comment by mdesmet** [comment]
I was able to reproduce the issue. Will try to fix it shortly.

**Comment by mdesmet** [comment]
I've released v0.5.3 fixing this issue. Please let me know if you have any issues.

**Comment by OHDMax** [comment]
Works like a charm now. Thanks for the update.

**Comment by callumwebb** [comment]
Amazing! Thanks for the speedy fix
