### ISSUE TITLE
features request for command palette

### ISSUE THREAD

**Issue by ivan-toriya** [innoverio/vscode-dbt-power-user#67]
1. `dbt Power User: Run current model` not working with tests. `dbt test` when the model runs from /tests/*
2. Ability to choose environment to use

**Comment by nirakon** [comment]
3. `dbt Power User: Run current model` not working with tests

**Comment by mdesmet** [comment]
1. Do you mean running the tests for a model? I think that might be useful.
2.  In my case running on any other environment than your own environment is handled by CI/CD (promotion to uat/prod), so I've never really needed to choose environments.

**Comment by mdesmet** [comment]
Tests is implemented in latest version.

Environment is raised in #124
