### ISSUE TITLE
Ref with package

### ISSUE THREAD

**Issue by AndreasTA-FF** [innoverio/vscode-dbt-power-user#68]
Hi!

I've looked around but haven't found any issues about this. 
Currently I can do {{ ref('some_table') }} and get autocomplete, but if I use the syntax {{ ref('some_package', 'some_table') }} it doesn't help me at all. Maybe I'm doing something wrong or it's not supported by the extension yet?
Everything is latest and greats.

Otherwise, great extension!

**Comment by mdesmet** [comment]
That is indeed currently not supported. Only the one parameter ref is supported. I have not yet have any use case for using ref with package name. Could you shine some light on your exact use case?

**Comment by AndreasTA-FF** [comment]
Ofc, I will try to shine some light on it :) 
We use multiple DBT projects and we use ref/sources between these. They way we do this is using packages.yaml and add other domains as dependencies. Doing it this way, we need to use ref('package','table') or source('pkg','table') to make sure we get the data from the correct project. Currently we use BigQuery so it might be different projects/datasets behind the scene.

Hope it makes some sense!

**Comment by mdesmet** [comment]
We also use extensively packags in our code. but never needed to use the package parameter. We simply ref('anotherModel') from another package. Why do you need to specify the package? Does this make it work if your model identifiers are duplicated?

**Comment by AndreasTA-FF** [comment]
Well, it doesn't support duplicated model identifiers yet, but they are working on it and I really hope it will be possible soon [1269](https://github.com/fishtown-analytics/dbt/issues/1269). Since we are spread out on multiple teams, we hope we don't have to care about clashes in the near future. Some reasons we would like to use the syntax ref('pkg','model') (same for sources) 

- prepared if it gets supported with duplicated model identifiers
- It makes the code easier to read, to know from where this model is originating.

**Comment by robertoash** [comment]
We are also using the `{{ ref('pkg', 'model') }}` syntax for some of the same reasons already mentioned by others. 

As well as the autocomplete, we are unable to navigate between the models using `Cmd + click` on the model name. That only works when using the `{{ ref('model') }}` syntax. 

Both syntaxes are [officially supported by DBT](https://docs.getdbt.com/reference/dbt-jinja-functions/ref#two-argument-variant) so it would be really nice if all features in the extension worked seamlessly regardless of which one has been chosen.

**Comment by mdesmet** [comment]
Sure, this change is definitely welcome! Are you willing to provide a PR for this feature?

**Comment by robertoash** [comment]
> Sure, this change is definitely welcome! Are you willing to provide a PR for this feature?

I guess you are talking to me. More than willing but sadly unable. Just don't know enough to be able to contribute 😞

**Comment by mdesmet** [comment]
fixed for models in 0.8.8. Let me know if it works.

**Comment by mdesmet** [comment]
This doesn't seem to apply on sources. Please correct me if I'm wrong.

**Comment by robertoash** [comment]
> fixed for models in 0.8.8. Let me know if it works.

Thank you so much for this!

The `Cmd + click` navigation works perfectly. Autocomplete I believe is also working as expected. 

We truly appreciate the helpful work you've put in!
