### ISSUE TITLE
Add "Run Current Model" Button

### ISSUE THREAD

**Issue by ajf1234** [innoverio/vscode-dbt-power-user#71]
There are play buttons for Run Model + Parents and Model + Children, but no button for just Run Current Model.

Great extension by the way, it really makes development in dbt so much easier!

**Comment by mdesmet** [comment]
This feature is still available although a bit hidden. It used to be displayed as a play button on the current screen.

![image](https://user-images.githubusercontent.com/9265503/124507019-327cb580-ddcd-11eb-9625-1c9b4a6f1557.png)

I can see if I can put it back, but I think vscode doesn't allow it, they probably don't want every extension to put their own buttons in the toolbar. I'll keep it open and let you know if I can find something.

If you like the extension, please rate us on https://marketplace.visualstudio.com/items?itemName=innoverio.vscode-dbt-power-user

**Comment by mdesmet** [comment]
Hi @ajf1234 ,

I've reenabled this feature, available in 0.5.6.

Let me know if it works!

**Comment by ajf1234** [comment]
@mdesmet Works like a charm! Thank you!
