### ISSUE TITLE
Slightly increase the time to check the dbt version installed

### ISSUE THREAD

**Issue by b-per** [innoverio/vscode-dbt-power-user#72]
With 0.5.4 and the introduction of a max time to check `dbt --version` of 5 secs, it is not showing up anymore on my computer, most likely because the command takes 7 secs to run locally.

Could the max time waiting for `dbt --version` to return be slightly increased to 10 or 15 secs?

**Comment by mdesmet** [comment]
Increased to 10s in 0.5.7. Let me know if that works for you!

**Comment by b-per** [comment]
I reloaded VS Code a few times to test it and got it working about half of the time (the other half of the time, the command times out and it doesn't show me the dbt version). 

Not sure if this is because of using WSL but sometimes the call for `dbt --version` takes a bit more than 10 secs. This is not too critical anyway so I can just close this one.

Cheers.
