### ISSUE TITLE
Create a language server implementation

### ISSUE THREAD

**Issue by joshuataylor** [innoverio/vscode-dbt-power-user#74]
Hi!

Last year I started looking into creating a similar project, but put on hold due to time commitments. Now I have more time, I started looking into creating a dbt-languageserver project, that would use the [language server protocol](https://microsoft.github.io/language-server-protocol/) so that multiple IDEs can use it -- this approach is used by [elixir-ls](https://github.com/elixir-lsp/elixir-ls), which then has a [specific project](https://github.com/elixir-lsp/vscode-elixir-ls) for vscode niceties (which this project has some fantastic vscode specific features!).

IMHO, it would be worth while splitting out the project into two repos (or even subfolders):
1. Language Server
2. VSCode specific extension (basically this extension, minus the LSP specific code)

What are your thoughts about this?

**Comment by mdesmet** [comment]
Hi Joshua,

I looked a bit into it when first starting the extension but it's a bit of a bigger undertaking compared to directly developing against the vscode api.  However I think it's definitely the right direction. Actually I think the most interesting part would be to combine not only dbt features but also SQL related features, for example providing autocompleting columns of tables etc. Such features would really enhance the developer experience but go somewhat beyond dbt.

I would be happy to discuss this and define a roadmap together. You can find me on the dbt slack channel under the same name.

**Comment by joshuataylor** [comment]
Awesome -- sorry for just dropping this random "issue" that isn't really an issue.

Yeah, there are lot of different editors and if there could be something similar to what elixir-ls is, the experience would be fantastic for those who have their favourite editors :rocket:.

I'm going to have to have a read through the code to see how things are done so far, and we would probably want to also figure out if the base extension should be written in python (which dbt is in, and easier to interface with?) or just stick with vscode-language-server typescript (which is great, then just read the manifest file which has everything in there, downside being that files need to be compiled for bigger changes).

**Comment by morgankrey** [comment]
Would love to revisit this a few years later - this would allow us at Zed (zed.dev) to support dbt power user within our Rust-based editor and bring y'all to our tens of thousands of users!
