### ISSUE TITLE
Cannot read manifest - target/{{target.name}}

### ISSUE THREAD

**Issue by YunJD** [innoverio/vscode-dbt-power-user#81]
I have set `target-path: target/{{target.name}}` in my `project.yaml` and it breaks the editor features.  Using `target` has no issue.

Works:
* dbt list
* play button to run/compile

Doesn't work:
* List model hierarchy
* Go to definition
* Anything related to tables (lookup, autocomplete, ...)

Discovered through console log where `target/{{target.name}}/manifest.json` could not be found.

Python: 3.8.7
DBT: 0.20.1

**Comment by mdesmet** [comment]
Jinja parsing is indeed not supported. It will however take the target-path in case it is a fixed value, also all compilations or runs will automatically take the default target. 

I would suggest to only use a default target (local development) and do other targets through CI builds or manual runs with a set target.
