### ISSUE TITLE
Configure default cli flags for dbt run button

### ISSUE THREAD

**Issue by tbescherer** [innoverio/vscode-dbt-power-user#88]
Hello! I just discovered this extension and I love it, thank you for making it!

One nice to have feature would be the ability to configure a set of command line flags that automatically get appended to the dbt run command.

For instance, when testing code in development I frequently use the dbt defer flag to save time on building upstream models [https://docs.getdbt.com/reference/node-selection/defer](https://docs.getdbt.com/reference/node-selection/defer) i.e. `dbt run --model model_1 --defer --state path/to/artifacts` instead of `dbt run --model model_1`

It would be great to be able to provide a config to dbt\_power\_user with the value \```--defer --state path/to/artifacts` `` or whatever other flags I wanted to use that would be automatically appended to the dbt run command every time I press the "run model" button.

**Comment by mdesmet** [comment]
HI @tbescherer,

Will be available in next release (0.5.9).

If you like it, please leave a review on https://marketplace.visualstudio.com/items?itemName=innoverio.vscode-dbt-power-user

![image](https://user-images.githubusercontent.com/9265503/139534703-641119f1-d1ca-4d48-9a21-3d7d9b64a40d.png)
