### ISSUE TITLE
Unreasonable amount of threads of python from dbt power user extension

### ISSUE THREAD

**Issue by reidwil-jb** [innoverio/vscode-dbt-power-user#89]
I am assuming the extension is running through my project but I have noticed the extension is the culprit for running up to 70 Python threads on my machine. 

This is most likely because it's trying to run some type of `dbt compile` in the background to get information about my project but very much don't think it's the right call to be running an this many threads on my machine. 

I can provide whatever information/diagnostics we would need to debug this.

**Note**: This has happened on my MacOS machine as well as a coworker's Windows machine.

**Comment by mdesmet** [comment]
Hi @reidwil-jb,

There is some queueing mechanism that shouldn't not run more than one dbt task in parallel, I have not seen the behavior that you describe. Is there any specific circumstance where this happens?

What is the output in the following screen?

![image](https://user-images.githubusercontent.com/9265503/141486603-c9dbecac-b49a-4a76-8233-e10eb3b67836.png)

**Comment by reidwil-jb** [comment]
Output of my terminal tasks:

![Screen Shot 2021-11-17 at 1 20 07 PM](https://user-images.githubusercontent.com/87150621/142259185-59c7ece4-26e8-4bed-a871-f51aff463beb.png)

**Comment by reidwil-jb** [comment]
Note: my dbt project has 16,000 models :'-)

**Comment by reidwil-jb** [comment]
@mdesmet I've found the culprit - checking out to different git branches from within my `zsh` shell triggers the dbt power user extension to execute a `dbt list`. 

----------
* I assume `dbt list` generates some artifact that is necessary to make sure the plugin can work correctly so it's imparative
* My case _might_  be a one off issue as the dbt project i'm working with is large
* What is the thread level set for the `dbt list` command?

**Comment by mdesmet** [comment]
Now every project uses a single Python process. Therefore I would expect this issue to be resolved. If not please reopen.
