### ISSUE TITLE
Configure additional parameters *between* `dbt` and `run`

### ISSUE THREAD

**Issue by thomasaarholt** [innoverio/vscode-dbt-power-user#90]
It would be nice to be able to specify extra options to the dbt run command. In particular, I like running 
`dbt --use-experimental-parser --partial-parse run -m my_model`. Here the two parser options won't work i they are passed to `dbt.runModelCommandAdditionalParams`, since these are added *after* the model.

**Comment by mdesmet** [comment]
Any argument of setting this up in dbt configuration?

https://docs.getdbt.com/reference/global-configs#experimental-parser
