### ISSUE TITLE
parameter "--profiles-dir"  doesn't work

### ISSUE THREAD

**Issue by p-pekala** [innoverio/vscode-dbt-power-user#91]
Setting --profiles-dir  in extension's settings doesn't affect run. In console I can see correctly:

dbt run --model customer_nation_region  --profiles-dir /path

but still seeing:

`Running with dbt=0.21.1
Encountered an error while reading the project:
  ERROR: Runtime Error
  Could not find profile named 'bigquery'
Encountered an error:
Runtime Error
  Could not run dbt`

Running the same command manually works perfectly.

**Comment by amirbtb** [comment]
Hi,
I have the same issue, I tried setting it using the `DBT_PROFILES_DIR` environment variable, move the `profiles.yml` to `.dbt` and the extension's settings but it does not work.
Do you mind explaining where to put the dbt project for this extension to work or implemeting a way to explicit the path to the profiles file ? 
Thank you 🙏🏽

**Comment by mdesmet** [comment]
You could try to set the environment variables within .vscode config for the project (config.terminal.integrated.env).

env: A map defining environment variables and their values, set the variable to null to delete it from the environment. This can be configured for all profiles using the terminal.integrated.env.<platform> setting.
See https://code.visualstudio.com/docs/editor/integrated-terminal

https://github.com/innoverio/vscode-dbt-power-user/blob/1be0a0a8a31f99d8a0b26e03f3bf8490ae5fdaac/src/dbt_client/index.ts#L178-L184
