### ISSUE TITLE
"dbt list" appears to hang at startup, "Parent Models" and "Children Models" is empty

### ISSUE THREAD

**Issue by smfritzii** [innoverio/vscode-dbt-power-user#94]
I'm relatively new to VS Code and DBT. I'm using VSCode via "Remote - SSH", dbt power user is installed in the correct SSH location. When I open a folder I get an "> Executing task:  dbt list" and it successfully lists all 60 models, then hangs hard - can't CTRL-C or anything. 

VSCode About:
Version: 1.60.2 (user setup)
Commit: 7f6ab5485bbc008386c4386d08766667e155244e
Date: 2021-09-22T12:00:31.514Z
Electron: 13.1.8
Chrome: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19042

Some other versions:
Ubuntu 20.04
dbt 0.21.0 
Python 3.8.0 
Remote - SSH 0.66.0
dbt Power User 0.5.9

**Comment by KyleWellendorff** [comment]
Im having the same issue. It renders the whole extension useless

**Comment by KyleWellendorff** [comment]
So I downloaded the extension: vscode-dbt-language: then ran the entire dbt project, so it created a manifest. and this new extension tells the other extensions where to find the manifest (where it find the relations to refs and code)

**Comment by KyleWellendorff** [comment]
appears to be working now. That should be on the dependencies list!!!!!!

**Comment by mdesmet** [comment]
> So I downloaded the extension: vscode-dbt-language: then ran the entire dbt project, so it created a manifest. and this new extension tells the other extensions where to find the manifest (where it find the relations to refs and code)

This is not correct information, that extension is not a dependency for this extension. 

Can you send me an example project that gives this issue?

**Comment by KyleWellendorff** [comment]
Well it may not be a dependency for , but it got half of the functionality working for me. So for my project, it appears that it did depend on this missing extension. At least for reading the manifest and going to REF definitions. Other than that, Compile, show SQL preview, and the child/parent model graphs still show up empty and 'dbt list' seems to just hang there and never finish (at least you cannot tell within the terminal. Cant CNTRL+C it).

**Comment by mdesmet** [comment]
Hi all,

We just checked with @KyleWellendorff : in his case  he has set target_path: {{ env_var('DBT_TARGET_PATH', 'target') }}

If you set it to target_path: "target", it will work

The extension doesn't support jinja syntax, so hence it doesn't work.

**Comment by KyleWellendorff** [comment]
Works like a charm now!
