### ISSUE TITLE
Setting path to dbt project 

### ISSUE THREAD

**Issue by picousse** [innoverio/vscode-dbt-power-user#95]
Hi,
I'm using dbt in a git repo.
Dbt is thus part of the project, and the whole dbt project is stored under a subfolder.

I'm using dbt in different envs as well.

Workflow:
Source env file (this defines where dbt can find the profiles)
and then go to the dbt subfolder, and run dbt from there.

- Is there a way for this extension to set the folder where the dbt project can be found?

**Comment by mdesmet** [comment]
Project discovery should work automatically, the extension searches your project to find any dbt_project.yml and registers the projects automatically. 

The env part can be handled in the following way (.env files are not supported at the moment, definitely open for PR's)

Just set the environment variables within .vscode config for the project (config.terminal.integrated.env).

env: A map defining environment variables and their values, set the variable to null to delete it from the environment. This can be configured for all profiles using the terminal.integrated.env.<platform> setting.
See https://code.visualstudio.com/docs/editor/integrated-terminal

https://github.com/innoverio/vscode-dbt-power-user/blob/1be0a0a8a31f99d8a0b26e03f3bf8490ae5fdaac/src/dbt_client/index.ts#L178-L184
