### ISSUE TITLE
Publish this extension to Open VSX Registry?

### ISSUE THREAD

**Issue by andrewcstewart** [innoverio/vscode-dbt-power-user#99]
Would you consider publishing this to https://open-vsx.org ?

It would be great to be able to install `vscode-dbt-power-user` [in GitPod](https://www.gitpod.io/docs/vscode-extensions)

https://github.com/eclipse/openvsx/wiki/Publishing-Extensions

**Comment by tylerssn** [comment]
I came here for the same reason. Would love to see this published to Open VSX. I tried a few hacks to get this to install in GitPod but the only way appears to be adding it to Open VSX.

**Comment by mdesmet** [comment]
I gave it a try, however it seems the publishing doesn't seem to support extensionDependencies.

Note that this extension is highly dependent on MS python extension

**Comment by bastienboutonnet** [comment]
Sure I'll have a look in the coming days!
